import { useState } from "react";
import { FiHeadphones, FiLogIn, FiMail, FiMenu, FiUserPlus, FiX } from "react-icons/fi";
import { Link, useNavigate } from "react-router-dom";
import SearchBar from "./SearchBar";
import MegaMenu from "./MegaMenu";

const links=[{label:"Support",icon:FiHeadphones,to:"/support"},{label:"Contact",icon:FiMail,to:"/contact"},{label:"Login",icon:FiLogIn,to:"/login"}];
export default function Navbar({searchValue="",onSearchChange}){
  const [open,setOpen]=useState(false);const navigate=useNavigate();
  const submit=()=>navigate(`/catalogue${searchValue?`?q=${encodeURIComponent(searchValue)}`:""}`);
  return <header className="sticky top-0 z-50 bg-white/95 backdrop-blur"><nav className="section-shell flex min-h-18 items-center gap-4 py-3" aria-label="Primary navigation"><Link to="/" className="shrink-0" aria-label="MB Store home"><img src="/assests/mb.png" alt="MB Store" className="h-15 w-41 rounded-lg object-contain"/></Link><div className="hidden flex-1 md:block"><SearchBar value={searchValue} onChange={onSearchChange} onSubmit={submit}/></div><div className="ml-auto hidden items-center gap-1 lg:flex">{links.map(({label,icon:Icon,to})=><Link key={label} to={to} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-sky-50 hover:text-sky-700"><Icon/>{label}</Link>)}<Link to="/register" className="ml-2 flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-red-700"><FiUserPlus/>Register</Link></div><Link to="/login" className="ml-auto rounded-lg bg-sky-600 px-4 py-2 text-sm font-bold text-white md:hidden">Login</Link><button className="rounded-lg p-2 text-2xl text-slate-700 lg:hidden" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label="Toggle navigation">{open?<FiX/>:<FiMenu/>}</button></nav><div className="section-shell pb-3 md:hidden"><SearchBar compact value={searchValue} onChange={onSearchChange} onSubmit={submit}/></div>{open&&<div id="mobile-menu" className="border-t border-slate-100 bg-white p-4 lg:hidden"><div className="section-shell grid gap-2">{links.slice(0,2).map(({label,icon:Icon,to})=><Link key={label} to={to} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl p-3 font-bold text-slate-700 hover:bg-sky-50"><Icon/>{label}</Link>)}<Link to="/register" onClick={()=>setOpen(false)} className="rounded-xl bg-red-600 p-3 text-center font-bold text-white">Register as Seller</Link></div></div>}<MegaMenu/></header>
}
