import { useEffect, useRef, useState } from "react";
import { FiGrid, FiHeadphones, FiLogIn, FiLogOut, FiMail, FiMenu, FiSettings, FiUser, FiUserPlus, FiX } from "react-icons/fi";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import SearchBar from "./SearchBar";
import MegaMenu from "./MegaMenu";

const publicLinks=[{label:"Support",icon:FiHeadphones,to:"/support"},{label:"Contact",icon:FiMail,to:"/contact"}];
const accountLinks=[{label:"Dashboard",icon:FiGrid,to:"/customer/home"},{label:"Profile",icon:FiUser,to:"/customer/profile"},{label:"Settings",icon:FiSettings,to:"/customer/settings"}];

function CustomerAccount() {
  const {user,logout}=useAuth(); const navigate=useNavigate(); const [open,setOpen]=useState(false); const container=useRef(null);
  useEffect(()=>{const close=event=>{if(!container.current?.contains(event.target))setOpen(false)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
  const leave=async()=>{setOpen(false);await logout();navigate("/",{replace:true})};
  return <div ref={container} className="relative"><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-haspopup="menu" aria-label="Open customer account menu" className="grid size-11 place-items-center rounded-full bg-sky-700 text-lg font-black text-white shadow-sm ring-4 ring-sky-100">{user?.name?.[0]?.toUpperCase()||<FiUser/>}</button>{open&&<div role="menu" className="absolute right-0 top-14 z-[80] w-56 overflow-hidden rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl"><div className="border-b border-slate-100 px-3 py-3"><p className="truncate text-sm font-black text-slate-900">{user.name}</p><p className="truncate text-xs text-slate-500">{user.email}</p></div>{accountLinks.map(({label,icon:Icon,to})=><Link role="menuitem" key={label} to={to} onClick={()=>setOpen(false)} className="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-slate-700 hover:bg-sky-50 hover:text-sky-700"><Icon/>{label}</Link>)}<button role="menuitem" onClick={leave} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-red-600 hover:bg-red-50"><FiLogOut/>Logout</button></div>}</div>;
}

export default function Navbar({searchValue="",onSearchChange}){
  const [open,setOpen]=useState(false); const navigate=useNavigate(); const {user}=useAuth(); const customer=user?.role==="Customer";
  const submit=()=>navigate(`/catalogue${searchValue?`?q=${encodeURIComponent(searchValue)}`:""}`);
  return <header className="sticky top-0 z-50 bg-white/95 backdrop-blur"><nav className="section-shell flex min-h-18 items-center gap-4 py-3" aria-label="Primary navigation"><Link to="/" className="shrink-0" aria-label="MB Store home"><img src="/assests/mb.png" alt="MB Store" className="h-15 w-41 rounded-lg object-contain"/></Link><div className="hidden flex-1 md:block"><SearchBar value={searchValue} onChange={onSearchChange} onSubmit={submit}/></div><div className="ml-auto hidden items-center gap-1 lg:flex">{publicLinks.map(({label,icon:Icon,to})=><Link key={label} to={to} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-slate-600 hover:bg-sky-50 hover:text-sky-700"><Icon/>{label}</Link>)}{customer?<CustomerAccount/>:<><Link to="/login" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-slate-600 hover:bg-sky-50 hover:text-sky-700"><FiLogIn/>Login</Link><Link to="/register" className="ml-2 flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-red-700"><FiUserPlus/>Register</Link></>}</div><div className="ml-auto lg:hidden">{customer?<CustomerAccount/>:<Link to="/login" className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-bold text-white">Login</Link>}</div><button className="rounded-lg p-2 text-2xl text-slate-700 lg:hidden" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label="Toggle navigation">{open?<FiX/>:<FiMenu/>}</button></nav><div className="section-shell pb-3 md:hidden"><SearchBar compact value={searchValue} onChange={onSearchChange} onSubmit={submit}/></div>{open&&<div id="mobile-menu" className="border-t border-slate-100 bg-white p-4 lg:hidden"><div className="section-shell grid gap-2">{publicLinks.map(({label,icon:Icon,to})=><Link key={label} to={to} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl p-3 font-bold text-slate-700 hover:bg-sky-50"><Icon/>{label}</Link>)}{!customer&&<Link to="/register" onClick={()=>setOpen(false)} className="rounded-xl bg-red-600 p-3 text-center font-bold text-white">Register</Link>}</div></div>}<MegaMenu/></header>;
}
