import { useMemo, useState } from "react";
import { FiChevronDown, FiRotateCcw, FiSearch } from "react-icons/fi";
import { brands } from "../data/brands";
import { categoryNames } from "../data/categories";
import { products } from "../data/products";

const companies=[...new Set(products.map(p=>p.company))];
const options={category:categoryNames,brand:brands,company:companies,power:[...new Set(products.map(p=>p.power))],voltage:[...new Set(products.map(p=>p.voltage))],technology:[...new Set(products.map(p=>p.technology))],availability:["In Stock","Available on Request"]};
const labels={category:"Category",brand:"Brand",company:"Company",power:"Power Rating",voltage:"Voltage",technology:"Technology",availability:"Availability"};

function FilterSection({type,values,selected,onToggle}){const [open,setOpen]=useState(true);const [showAll,setShowAll]=useState(false);const [query,setQuery]=useState("");const shown=useMemo(()=>values.filter(v=>v.toLowerCase().includes(query.toLowerCase())).slice(0,showAll?values.length:6),[values,query,showAll]);return <div className="border-b border-slate-200 py-5"><button onClick={()=>setOpen(!open)} aria-expanded={open} className="flex w-full items-center justify-between text-left text-sm font-black text-slate-900">{labels[type]}<FiChevronDown className={`transition ${open?"rotate-180":""}`}/></button>{open&&<div className="mt-4">{type==="brand"&&<div className="relative mb-3"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search brands" placeholder="Search brands" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-xs outline-none focus:border-sky-400"/></div>}<div className="max-h-52 space-y-2 overflow-y-auto pr-1">{shown.map(value=><label key={value} className="flex cursor-pointer items-center gap-2.5 text-xs text-slate-600 hover:text-sky-700"><input type="checkbox" checked={selected.includes(value)} onChange={()=>onToggle(type,value)} className="h-4 w-4 rounded border-slate-300 accent-sky-600"/><span className="truncate">{value}</span></label>)}</div>{values.length>6&&<button onClick={()=>setShowAll(!showAll)} className="mt-3 text-xs font-extrabold text-sky-700">{showAll?"Show Less":"Show More"}</button>}</div>}</div>}

export default function SidebarFilters({filters,onToggle,onReset,className=""}){return <aside className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`} aria-label="Product filters"><div className="flex items-center justify-between"><h2 className="font-black text-slate-900">Filters</h2><button onClick={onReset} className="flex items-center gap-1 text-xs font-bold text-red-600"><FiRotateCcw/>Reset</button></div>{Object.entries(options).map(([type,values])=><FilterSection key={type} type={type} values={values} selected={filters[type]} onToggle={onToggle}/>)}</aside>}
