import { useCallback, useEffect, useMemo, useState } from "react";
import { FiCheckCircle, FiEdit2, FiSave, FiX } from "react-icons/fi";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";
import CustomerLayout from "../../layout/customer/CustomerLayout";

const customerSections = [["Personal Information",[["customerId","Customer ID",true],["customerName","Customer Name"],["email","Email"],["phoneNumber","Phone Number"]]],["Address Information",[["address","Address"],["state","State"],["district","District"],["area","Area"],["landmark","Landmark"]]]];
const sellerSections = [["Personal Information",[["sellerId","Seller ID",true],["sellerName","Seller Name"],["email","Email"],["phoneNumber","Phone Number"]]],["Business Information",[["companyName","Company Name"],["businessEmail","Business Email"],["gst","GST"],["website","Website"]]],["Address Information",[["address","Address"],["state","State"],["district","District"],["area","Area"],["landmark","Landmark"]]]];

export function ProfileContent({ role }) { const lower=role.toLowerCase(); const sections=role==="Seller"?sellerSections:customerSections; const {toast}=useToast(); const [profile,setProfile]=useState(null); const [form,setForm]=useState({}); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false);
  const load=useCallback(()=>api.get(`/${lower}/profile`).then(({data})=>{setProfile(data.profile);setForm(data.profile)}).catch(e=>toast(apiMessage(e),"error")),[lower,toast]); useEffect(()=>{load()},[load]);
  const missing=useMemo(()=>new Set(profile?.missingFields||[]),[profile]); const save=async()=>{setSaving(true);try{const {data}=await api.put(`/${lower}/profile`,form);setProfile(data.profile);setForm(data.profile);setEditing(false);window.dispatchEvent(new CustomEvent(`mb:${lower}-profile-updated`,{detail:data.profile}));toast(data.message)}catch(e){toast(apiMessage(e),"error")}finally{setSaving(false)}};
  if(!profile)return <div className="space-y-4">{[1,2,3].map(x=><div key={x} className="h-36 animate-pulse rounded-2xl bg-slate-200"/>)}</div>;
  return <div className="mx-auto max-w-5xl space-y-6"><section className="rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-300">{role} profile</p><h1 className="mt-2 text-3xl font-black">Profile Completion</h1><p className="mt-2 text-sm text-slate-300">Keep your details accurate and up to date.</p></div><strong className="text-4xl text-teal-300">{profile.profileCompletion}%</strong></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-teal-400" style={{width:`${profile.profileCompletion}%`}}/></div>{role==="Seller"&&<p className="mt-4 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><FiCheckCircle/>Status: {profile.verificationStatus}</p>}</section>
  {sections.map(([title,fields])=><section key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">{title}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{fields.map(([key,label,readOnly])=><label key={key} className="text-sm font-bold text-slate-600">{label}{editing&&!readOnly?<input value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})} className={`mt-2 w-full rounded-xl border px-4 py-3 font-normal outline-none focus:border-teal-600 ${missing.has(key)?"border-amber-300 bg-amber-50/40":"border-slate-200"}`}/>:<p className="mt-2 min-h-6 font-semibold text-slate-900">{profile[key]||<span className="font-normal text-slate-400">Not provided</span>}</p>}</label>)}</div></section>)}
  <div className="flex justify-end gap-3">{editing?<><button onClick={()=>{setEditing(false);setForm(profile)}} className="flex items-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold"><FiX/>Cancel</button><button disabled={saving} onClick={save} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><FiSave/>{saving?"Saving...":"Save Changes"}</button></>:<button onClick={()=>setEditing(true)} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white"><FiEdit2/>Edit Profile</button>}</div></div>;
}
export function CustomerProfilePage(){return <CustomerLayout title="Profile"><ProfileContent role="Customer"/></CustomerLayout>}
export function SellerProfilePage(){return <ProfileContent role="Seller"/>}
