import {Link} from "react-router-dom";
import {motion} from "framer-motion";
import {HiOutlineBuildingOffice2,HiOutlineCube,HiOutlinePhoto} from "react-icons/hi2";
import {apiAsset} from "../../lib/api";

export default function FeaturedProducts({products=[],loading=false}) {
  return <motion.section initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="rounded-[20px] border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-900">Featured Products</h2><p className="mt-1 text-sm text-slate-500">Products customers request quotations for most often.</p></div><Link to="/catalogue" className="text-sm font-semibold text-teal-700">View All</Link></div>
    {loading?<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-80 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:products.length?<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{products.map((product,index)=><motion.article key={product.id} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:index*.05}} className="overflow-hidden rounded-2xl border border-slate-200"><div className="grid h-44 place-items-center bg-slate-100">{product.imageUrl?<img src={apiAsset(product.imageUrl)} alt={product.productName} className="h-full w-full object-cover"/>:<HiOutlinePhoto className="text-5xl text-slate-400"/>}</div><div className="p-5"><h3 className="line-clamp-2 text-lg font-bold">{product.productName}</h3><p className="mt-3 flex items-center gap-2 text-sm text-slate-500"><HiOutlineBuildingOffice2/>{product.sellerCompany}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><HiOutlineCube/>{product.categoryName}</p><p className="mt-4 text-xs font-bold text-teal-700">{product.quotationCount} quotation request{product.quotationCount===1?"":"s"}</p><Link to={`/catalogue?search=${encodeURIComponent(product.productName)}`} className="mt-5 block rounded-xl border px-4 py-2 text-center text-sm font-semibold">View Product</Link></div></motion.article>)}</div>:<p className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">Featured products will appear after customers request quotations.</p>}
  </motion.section>;
}
