import {motion} from "framer-motion";
import {HiOutlineDocumentText,HiOutlineEye} from "react-icons/hi2";

const relativeTime=value=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value))/1000));if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;if(seconds<604800)return `${Math.floor(seconds/86400)}d ago`;return new Date(value).toLocaleDateString("en-IN")};

export default function RecentActivity({activities=[],loading=false}) {
  return <motion.section initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="rounded-[20px] border border-slate-200 bg-white p-6 shadow-sm">
    <div className="mb-6"><h2 className="text-xl font-bold text-slate-900">Recent Activity</h2><p className="mt-1 text-sm text-slate-500">Products you viewed and quotation requests you raised.</p></div>
    {loading?<div className="h-48 animate-pulse rounded-2xl bg-slate-100"/>:activities.length?<div className="max-h-[34rem] space-y-3 overflow-y-auto pr-1">{activities.map((activity,index)=>{const viewed=activity.type==="view",Icon=viewed?HiOutlineEye:HiOutlineDocumentText;return <motion.article key={`${activity.type}-${activity.id}`} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:Math.min(index,8)*.04}} className="flex gap-4 rounded-2xl border border-slate-100 bg-slate-50 p-4"><span className={`grid size-11 shrink-0 place-items-center rounded-full ${viewed?"bg-blue-100 text-blue-600":"bg-emerald-100 text-emerald-600"}`}><Icon className="text-xl"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold text-slate-900">{viewed?`Viewed ${activity.productName}`:"Quotation requested"}</h3><time className="text-xs text-slate-400">{relativeTime(activity.occurredAt)}</time></div><p className="mt-1 text-sm text-slate-600">{viewed?`${activity.brand} · Viewed ${activity.viewCount} time${activity.viewCount===1?"":"s"}`:`${activity.productName} from ${activity.sellerCompany} · ${activity.quotationNumber}`}</p>{!viewed&&<span className="mt-2 inline-block rounded-full bg-white px-2.5 py-1 text-xs font-bold capitalize text-slate-600">{activity.status}</span>}</div></motion.article>})}</div>:<p className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">Your product views and quotation requests will appear here.</p>}
  </motion.section>;
}
