import {useCallback,useEffect,useMemo,useState} from "react";
import {FiActivity,FiBox,FiCalendar,FiCheckCircle,FiClock,FiFileText,FiMapPin,FiRefreshCw,FiUsers} from "react-icons/fi";
import {useNavigate} from "react-router-dom";
import {Area,AreaChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import api,{apiAsset,apiMessage} from "../../lib/api";
import {useToast} from "../../context/ToastContext";
import {getSellerDashboard} from "../../services/sellerDashboardService";

const card="rounded-[20px] border border-slate-200 bg-white shadow-[0_4px_24px_rgba(15,23,42,.04)]";
const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function current(){const now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;return{month,from:`${month}-01`,to:iso(now),grouping:"day"}}
const statusTone={pending:"bg-amber-50 text-amber-700",quoted:"bg-blue-50 text-blue-700",accepted:"bg-emerald-50 text-emerald-700",declined:"bg-red-50 text-red-700",rejected:"bg-red-50 text-red-700"};

export default function SellerDashboard(){
  const {toast}=useToast(),navigate=useNavigate(),initial=useMemo(current,[]);
  const [draft,setDraft]=useState(initial),[filters,setFilters]=useState(initial),[data,setData]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [{data:dashboard},{data:profileData}]=await Promise.all([getSellerDashboard(filters),api.get("/seller/profile")]);setData(dashboard);setProfile(profileData.profile)}catch(requestError){setError("Unable to load seller dashboard.");toast(apiMessage(requestError),"error")}finally{setLoading(false)}},[filters,toast]);
  useEffect(()=>{load()},[load]);
  function month(value){if(!value)return setDraft({...draft,month:""});const [year,number]=value.split("-").map(Number),today=new Date(),end=new Date(year,number,0),to=year===today.getFullYear()&&number===today.getMonth()+1?today:end;setDraft({...draft,month:value,from:`${value}-01`,to:iso(to)})}
  function apply(){if(!draft.from||!draft.to||draft.from>draft.to)return toast("Select a valid date range.","error");setFilters({...draft})}
  const pipeline=data?.pipeline||{};
  const pipelineItems=[["Total Leads",pipeline.totalLeads,FiUsers,"bg-violet-50 text-violet-600"],["Enquiries",pipeline.enquiries,FiFileText,"bg-blue-50 text-blue-600"],["Quotations",pipeline.quotations,FiFileText,"bg-amber-50 text-amber-600"],["Converted",pipeline.converted,FiCheckCircle,"bg-emerald-50 text-emerald-600"],["Active Products",pipeline.activeProducts,FiBox,"bg-sky-50 text-sky-600"],["Conversion Rate",`${pipeline.conversionRate||0}%`,FiActivity,"bg-rose-50 text-rose-600"]];
  return <><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-500">Seller workspace</p><h1 className="mt-1 text-2xl font-black">Welcome back, {profile?.sellerName||"Seller"}</h1><p className="mt-1 text-sm text-slate-500">{profile?.companyName||"Your company"} · Live business activity and performance.</p></div>{data?.updatedAt&&<p className="text-xs text-slate-400">Updated {new Date(data.updatedAt).toLocaleString("en-IN")}</p>}</div>
  <section className={`${card} mb-5 p-4`}><div className="flex flex-wrap items-end gap-3"><label className="text-[11px] font-black uppercase tracking-wider text-slate-400">Month<input type="month" value={draft.month} onChange={e=>month(e.target.value)} className="mt-1 block h-11 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700 outline-teal-600"/></label><label className="text-[11px] font-black uppercase tracking-wider text-slate-400">From<input type="date" value={draft.from} onChange={e=>setDraft({...draft,month:"",from:e.target.value})} className="mt-1 block h-11 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700 outline-teal-600"/></label><label className="text-[11px] font-black uppercase tracking-wider text-slate-400">To<input type="date" value={draft.to} onChange={e=>setDraft({...draft,month:"",to:e.target.value})} className="mt-1 block h-11 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700 outline-teal-600"/></label><label className="text-[11px] font-black uppercase tracking-wider text-slate-400">Time Rate<select value={draft.grouping} onChange={e=>setDraft({...draft,grouping:e.target.value})} className="mt-1 block h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 outline-teal-600"><option value="day">Daily</option><option value="month">Monthly</option></select></label><button onClick={apply} className="h-11 rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Apply</button><button disabled={loading} onClick={load} className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-600 disabled:opacity-50"><FiRefreshCw className={loading?"animate-spin":""}/>Refresh</button></div></section>
  {error&&<div className="mb-5 rounded-2xl bg-red-50 p-4 text-red-700"><b>{error}</b><button onClick={load} className="ml-4 underline">Try again</button></div>}
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(360px,1fr)]"><section className={`${card} p-5 sm:p-6`}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-400">Business Activity</p><h2 className="mt-1 text-lg font-black">Customers, Requests & Quotations</h2></div><FiCalendar className="text-slate-300"/></div><div className="mt-4 h-72">{loading?<Skeleton/>:data?.graph?.length?<ResponsiveContainer><AreaChart data={data.graph}><defs><linearGradient id="customers" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6366f1" stopOpacity=".2"/><stop offset="1" stopColor="#6366f1" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#eef0f7" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#94a3b8"}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#94a3b8"}}/><Tooltip contentStyle={{borderRadius:12,border:0,boxShadow:"0 8px 30px #0001"}}/><Legend iconType="circle" wrapperStyle={{fontSize:11}}/><Area name="Customers" type="monotone" dataKey="customers" stroke="#6366f1" fill="url(#customers)" strokeWidth={2}/><Area name="Product Requests" type="monotone" dataKey="productRequests" stroke="#14b8a6" fill="transparent" strokeWidth={2}/><Area name="Quotations" type="monotone" dataKey="quotations" stroke="#f59e0b" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<Empty text="No business activity for this period."/>}</div></section><section className={`${card} p-5`}><h2 className="font-black">Lead Pipeline</h2><div className="mt-5 grid grid-cols-2 gap-3">{pipelineItems.map(([name,value,Icon,tone])=><article key={name} className="rounded-2xl bg-slate-50 p-4"><span className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon/></span><strong className="mt-3 block text-2xl">{loading?"—":value??0}</strong><p className="mt-1 text-xs font-semibold text-slate-500">{name}</p></article>)}</div></section></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><ProductSummary loading={loading} rows={data?.products||[]} onOpen={id=>navigate(`/seller/products/${id}/edit`)}/><LocationBlock loading={loading} rows={data?.locations||[]}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.8fr]"><RecentLeads loading={loading} rows={data?.recentEnquiries||[]} onView={()=>navigate("/seller/leads")}/><RecentEnquiries loading={loading} rows={data?.recentEnquiries||[]} onView={()=>navigate("/seller/leads")}/></div></>;
}

function ProductSummary({loading,rows,onOpen}){return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Product Summary</h2><p className="mt-1 text-xs text-slate-400">Click a product to open its details.</p></div><div className="max-h-96 overflow-auto"><table className="w-full min-w-170 text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-xs text-slate-400"><tr>{["Product","Category","Brand","Views","Enquiries","Status"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{!loading&&rows.map(x=><tr key={x.id} onClick={()=>onOpen(x.id)} className="cursor-pointer transition hover:bg-teal-50/40"><td className="px-5 py-3"><div className="flex items-center gap-3">{x.imageUrl?<img src={apiAsset(x.imageUrl)} alt="" className="size-10 rounded-xl object-cover"/>:<span className="grid size-10 place-items-center rounded-xl bg-slate-100"><FiBox/></span>}<b>{x.productName}</b></div></td><td className="px-5 text-slate-500">{x.categoryName}</td><td className="px-5">{x.brand}</td><td className="px-5">{x.views}</td><td className="px-5">{x.enquiries}</td><td className="px-5 capitalize">{x.status}</td></tr>)}</tbody></table>{loading?<div className="p-5"><Skeleton/></div>:!rows.length&&<Empty text="No products found."/>}</div></section>}
function LocationBlock({loading,rows}){const max=Math.max(...rows.map(x=>x.total),1);return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Top Lead Locations</h2></div><div className="max-h-96 overflow-y-auto p-5">{loading?<Skeleton/>:rows.length?rows.map((x,i)=><div key={x.location} className="mb-5 flex items-center gap-3 last:mb-0"><b className="grid size-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-xs">{i+1}</b><div className="min-w-0 flex-1"><div className="flex justify-between gap-3 text-xs"><span className="truncate font-bold">{x.location}</span><span>{x.total}</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${(x.total/max)*100}%`}}/></div></div></div>):<Empty text="No customer locations available."/>}</div></section>}
function RecentLeads({loading,rows,onView}){return <section className={`${card} overflow-hidden`}><div className="flex items-center justify-between border-b border-slate-100 p-5"><h2 className="font-black">Recent Leads</h2><button onClick={onView} className="text-xs font-bold text-indigo-600">View all</button></div><div className="max-h-96 overflow-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs text-slate-400"><tr>{["Lead ID","Customer","Product","Location","Date","Status"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(x=><tr key={x.id}><td className="px-4 py-4 font-mono text-xs">{x.quotationNumber}</td><td className="px-4 font-bold">{x.customer}</td><td className="px-4">{x.product}</td><td className="px-4 text-slate-500">{x.location}</td><td className="px-4 text-slate-500">{new Date(x.createdAt).toLocaleDateString("en-IN")}</td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusTone[x.status]||"bg-slate-100"}`}>{x.status}</span></td></tr>)}</tbody></table>{loading?<div className="p-5"><Skeleton/></div>:!rows.length&&<Empty text="No recent leads."/>}</div></section>}
function RecentEnquiries({loading,rows,onView}){return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Recent Enquiries</h2><p className="mt-1 text-xs text-slate-400">Latest 10 customer requests</p></div><div className="max-h-96 overflow-y-auto">{loading?<div className="p-5"><Skeleton/></div>:rows.length?rows.map(x=><button key={x.id} onClick={onView} className="flex w-full gap-3 border-b border-slate-100 p-4 text-left transition last:border-0 hover:bg-slate-50"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{x.customer.split(" ").map(y=>y[0]).join("").slice(0,2)}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{x.customer}</b><span className="block truncate text-xs text-slate-500">{x.quantity} units · {x.product}</span><small className="mt-1 flex items-center gap-1 text-slate-400"><FiClock/>{new Date(x.createdAt).toLocaleString("en-IN")}</small></span><FiMapPin className="shrink-0 text-slate-300"/></button>):<Empty text="No recent enquiries."/>}</div></section>}
const Skeleton=()=> <div className="h-full min-h-28 animate-pulse rounded-2xl bg-slate-100"/>;
const Empty=({text})=><div className="grid min-h-32 place-items-center p-5 text-center text-sm font-bold text-slate-400">{text}</div>;
