import {useCallback,useEffect,useState} from "react";
import {FiBox,FiChevronLeft,FiChevronRight,FiEdit2,FiEye,FiImage,FiPlus,FiSearch,FiTrash2,FiX} from "react-icons/fi";
import {Link} from "react-router-dom";
import {motion} from "framer-motion";
import {getCategories} from "../../services/categoryService";
import {deleteProduct,getSellerProduct,getSellerProducts} from "../../services/productService";
import {apiMessage} from "../../lib/api";
import {useToast} from "../../context/ToastContext";

const availability={in_stock:["In Stock","bg-emerald-50 text-emerald-700"],low_stock:["Low Stock","bg-amber-50 text-amber-700"],out_of_stock:["Out of Stock","bg-red-50 text-red-700"]};
function Availability({value}){const [label,tone]=availability[value]||availability.in_stock;return <span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-bold ${tone}`}>{label}</span>}

export default function Products(){
  const {toast}=useToast();
  const [rows,setRows]=useState([]),[stats,setStats]=useState({}),[categories,setCategories]=useState([]),[brands,setBrands]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[categoryId,setCategoryId]=useState(""),[status,setStatus]=useState(""),[brand,setBrand]=useState(""),[sort,setSort]=useState("newest"),[page,setPage]=useState(1),[meta,setMeta]=useState({totalPages:1}),[view,setView]=useState(null),[remove,setRemove]=useState(null);
  useEffect(()=>{getCategories().then(({data})=>setCategories(data.data)).catch(()=>{})},[]);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1)},300);return()=>clearTimeout(timer)},[search]);
  const load=useCallback(async({silent=false}={})=>{if(!silent)setLoading(true);try{const {data}=await getSellerProducts({search:query||undefined,categoryId:categoryId||undefined,status:status||undefined,brand:brand||undefined,sort,page,limit:20});setRows(data.data);setStats(data.stats);setBrands(data.brands);setMeta(data)}catch(error){if(!silent)toast(apiMessage(error),"error")}finally{if(!silent)setLoading(false)}},[query,categoryId,status,brand,sort,page,toast]);
  useEffect(()=>{load();const timer=window.setInterval(()=>load({silent:true}),3000);return()=>window.clearInterval(timer)},[load]);
  const show=async id=>{try{const {data}=await getSellerProduct(id);setView(data.product)}catch(error){toast(apiMessage(error),"error")}};
  const confirmDelete=async()=>{try{await deleteProduct(remove.id);toast("Product deleted successfully.");setRemove(null);await load()}catch(error){toast(apiMessage(error),"error")}};
  const cards=[["Total Products",stats.totalProducts||0,"bg-violet-50 text-violet-700"],["Active Products",stats.activeProducts||0,"bg-emerald-50 text-emerald-700"],["Suspended",stats.suspendedProducts||0,"bg-red-50 text-red-700"],["Pending Products",stats.pendingProducts||0,"bg-amber-50 text-amber-700"],["Draft Products",stats.draftProducts||0,"bg-slate-100 text-slate-600"]];
  const change=setter=>event=>{setter(event.target.value);setPage(1)};
  return <><div className="mx-auto max-w-[1700px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-violet-600">Seller catalogue</p><h1 className="mt-1 text-3xl font-black">My Products</h1><p className="mt-1 text-sm text-slate-500">Manage your products and product listings.</p></div><Link to="/seller/products/new" className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/>Add Product</Link></div>
  <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,tone])=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><span className={`grid size-10 place-items-center rounded-xl ${tone}`}><FiBox/></span><p className="mt-3 text-sm text-slate-500">{label}</p><strong className="text-3xl">{value}</strong></article>)}</div>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><label className="flex min-w-60 flex-1 items-center gap-2 rounded-xl border px-4 py-2.5"><FiSearch/><input value={search} onChange={event=>setSearch(event.target.value)} className="w-full outline-none" placeholder="Search name, brand, category or product ID..."/></label><select value={categoryId} onChange={change(setCategoryId)} className="rounded-xl border px-3"><option value="">All categories</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={status} onChange={change(setStatus)} className="rounded-xl border px-3"><option value="">All statuses</option>{["active","suspended","pending","draft","inactive"].map(item=><option key={item}>{item}</option>)}</select><select value={brand} onChange={change(setBrand)} className="rounded-xl border px-3"><option value="">All brands</option>{brands.map(item=><option key={item}>{item}</option>)}</select><select value={sort} onChange={change(setSort)} className="rounded-xl border px-3"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="az">A-Z</option></select></div>
  <div className="overflow-x-auto"><table className="w-full min-w-275 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{["Image","Product Name","Category","Brand","Availability","Status","Views","Enquiries","Created","Actions"].map(item=><th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y">{loading?Array.from({length:5},(_,i)=><tr key={i}>{Array.from({length:10},(_,j)=><td className="px-4 py-4" key={j}><div className="h-4 animate-pulse rounded bg-slate-200"/></td>)}</tr>):rows.length?rows.map(row=><tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3">{row.imageUrl?<img src={row.imageUrl} alt="" className="size-12 rounded-xl object-cover"/>:<span className="grid size-12 place-items-center rounded-xl bg-slate-100 text-slate-400"><FiImage/></span>}</td><td className="px-4"><b>{row.productName}</b><small className="block font-mono text-slate-400">{row.productCode}</small></td><td className="px-4">{row.categoryName}</td><td className="px-4">{row.brand}</td><td className="px-4"><Availability value={row.availability}/></td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{row.status}</span></td><td className="px-4">{row.views}</td><td className="px-4">{row.enquiries}</td><td className="px-4">{new Date(row.createdAt).toLocaleDateString()}</td><td className="px-4"><div className="flex gap-2"><button onClick={()=>show(row.id)} className="rounded-lg border p-2"><FiEye/></button><Link to={`/seller/products/${row.id}/edit`} className="rounded-lg border p-2 text-blue-600"><FiEdit2/></Link><button onClick={()=>setRemove(row)} className="rounded-lg border p-2 text-red-600"><FiTrash2/></button></div></td></tr>):<tr><td colSpan="10" className="py-16 text-center"><FiBox className="mx-auto text-4xl text-slate-300"/><p className="mt-3 font-bold">You haven't added any products yet.</p><Link to="/seller/products/new" className="mt-4 inline-flex rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/> Add Product</Link></td></tr>}</tbody></table></div>
  <div className="flex justify-between border-t p-4"><span>Page {page} of {meta.totalPages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronLeft/></button><button disabled={page>=meta.totalPages} onClick={()=>setPage(value=>value+1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronRight/></button></div></div></section></div>
  {view&&<Modal title={view.productName} close={()=>setView(null)}><div className="mt-5 grid grid-cols-2 gap-3">{[["Product ID",view.productCode],["Category",view.categoryName],["Brand",view.brand],["Status",view.status],["Views",view.views],["Enquiries",view.enquiries]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><small className="text-slate-400">{label}</small><b className="block">{value}</b></div>)}</div><div className="mt-4"><small className="text-slate-400">Availability</small><div className="mt-2"><Availability value={view.availability}/></div></div><p className="mt-4 text-sm text-slate-600">{view.description}</p><h3 className="mt-5 font-black">Product Attributes</h3><div className="mt-2 divide-y rounded-xl border">{view.attributeDetails?.map(item=><div key={item.fieldKey} className="flex justify-between px-4 py-3 text-sm"><span>{item.fieldLabel}</span><b>{item.fieldValue}</b></div>)}</div></Modal>}
  {remove&&<Modal title="Delete Product?" close={()=>setRemove(null)}><p className="mt-4 text-slate-600">Are you sure you want to delete {remove.productName}? This product will be removed from your listings.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setRemove(null)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button onClick={confirmDelete} className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white">Delete</button></div></Modal>}</>;
}

function Modal({title,close,children}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}><FiX/></button></div>{children}</motion.div></div>}
