import {useEffect,useState} from "react";
import {FiBell,FiCheck,FiEye,FiPackage,FiRefreshCw,FiSettings,FiUser} from "react-icons/fi";
import api,{apiMessage} from "../../lib/api";
import {useAuth} from "../../context/AuthContext";
import {useToast} from "../../context/ToastContext";
import {getSellerSettings,updateSellerSettings} from "../../services/sellerSettingsService";

const card="rounded-[20px] border border-slate-200 bg-white shadow-[0_4px_24px_rgba(15,23,42,.04)]";
const tabs=[["Profile",FiUser],["Notifications",FiBell],["Catalogue",FiPackage],["Account",FiSettings]];

export default function SellerSettings(){
  const {toast}=useToast(),{refresh}=useAuth();
  const [tab,setTab]=useState("Profile"),[profile,setProfile]=useState({sellerName:""}),[settings,setSettings]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([api.get("/seller/profile"),getSellerSettings()]).then(([profileResponse,settingsResponse])=>{setProfile({sellerName:profileResponse.data.profile.sellerName||""});setSettings(settingsResponse.data.settings)}).catch(error=>toast(apiMessage(error),"error")).finally(()=>setLoading(false))},[toast]);
  async function saveProfile(event){event.preventDefault();setSaving(true);try{await api.put("/seller/profile",profile);await refresh({showLoader:false});window.dispatchEvent(new Event("mb:seller-profile-updated"));toast("Profile name updated successfully.")}catch(error){toast(apiMessage(error),"error")}finally{setSaving(false)}}
  async function saveSettings(){setSaving(true);try{const {data}=await updateSellerSettings(settings);setSettings(data.settings);toast(data.message)}catch(error){toast(apiMessage(error),"error")}finally{setSaving(false)}}
  if(loading)return <div className="space-y-5"><div className="h-16 animate-pulse rounded-2xl bg-white"/><div className="h-96 animate-pulse rounded-2xl bg-white"/></div>;
  return <><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.16em] text-violet-600">Seller workspace</p><h1 className="mt-1 text-3xl font-black">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage your profile, notifications, catalogue visibility and account preferences.</p></div><section className={`${card} overflow-hidden`}><nav className="flex overflow-x-auto border-b border-slate-200 px-3 sm:px-5">{tabs.map(([name,Icon])=><button key={name} onClick={()=>setTab(name)} className={`flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-4 text-sm font-bold transition ${tab===name?"border-teal-700 text-teal-700":"border-transparent text-slate-400 hover:text-slate-700"}`}><Icon/>{name}</button>)}</nav><div className="max-w-3xl p-5 sm:p-7">{tab==="Profile"&&<ProfileTab profile={profile} setProfile={setProfile} saving={saving} onSubmit={saveProfile}/>} {tab==="Notifications"&&<SettingsTab title="Notification Preferences" copy="Choose which seller activity creates notifications on your Notifications page." icon={FiBell}><Toggle label="Enable Notifications" description="Receive notifications in your seller workspace." checked={settings.notificationsEnabled} onChange={value=>setSettings({...settings,notificationsEnabled:value})}/><Toggle label="Quotation Notifications" description="Notify me when customers request, accept or decline quotations." checked={settings.quotationNotifications} disabled={!settings.notificationsEnabled} onChange={value=>setSettings({...settings,quotationNotifications:value})}/><Save saving={saving} onClick={saveSettings}/></SettingsTab>} {tab==="Catalogue"&&<SettingsTab title="Catalogue Settings" copy="Control how your products appear to customers in the public catalogue." icon={FiEye}><Toggle label="Show My Products" description="Display all of your active products in the public catalogue." checked={settings.showProducts} onChange={value=>setSettings({...settings,showProducts:value})}/><Toggle label="Show Availability" description="Display Available, Low Stock or Out of Stock on product cards." checked={settings.showAvailability} disabled={!settings.showProducts} onChange={value=>setSettings({...settings,showAvailability:value})}/><Save saving={saving} onClick={saveSettings}/></SettingsTab>} {tab==="Account"&&<SettingsTab title="Account Preferences" copy="Manage optional communications for your seller account." icon={FiSettings}><Toggle label="Email Updates" description="Receive important MB Store product and account updates by email." checked={settings.emailUpdates} onChange={value=>setSettings({...settings,emailUpdates:value})}/><Toggle label="Weekly Business Summary" description="Receive a weekly summary of leads, quotations and product demand." checked={settings.weeklySummary} onChange={value=>setSettings({...settings,weeklySummary:value})}/><Save saving={saving} onClick={saveSettings}/></SettingsTab>}</div></section></>;
}

function ProfileTab({profile,setProfile,saving,onSubmit}){return <form onSubmit={onSubmit}><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-teal-50 text-teal-700"><FiUser/></span><div><h2 className="text-lg font-black">Profile Name</h2><p className="mt-1 text-sm text-slate-500">This name is shown in your seller navigation and business profile.</p></div></div><label className="mt-6 block text-sm font-bold text-slate-700">Seller Name<input required minLength="2" maxLength="120" value={profile.sellerName} onChange={event=>setProfile({sellerName:event.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none transition focus:border-teal-600 focus:ring-3 focus:ring-teal-100"/></label><Save saving={saving}/></form>}
function SettingsTab({title,copy,icon:Icon,children}){return <div><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon/></span><div><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">{copy}</p></div></div><div className="mt-6 divide-y divide-slate-100 rounded-2xl border border-slate-200 px-4 sm:px-5">{children}</div></div>}
function Toggle({label,description,checked,onChange,disabled=false}){return <label className={`flex items-center justify-between gap-5 py-5 ${disabled?"opacity-45":"cursor-pointer"}`}><span><b className="block text-sm text-slate-800">{label}</b><small className="mt-1 block leading-5 text-slate-500">{description}</small></span><input type="checkbox" className="peer sr-only" checked={checked} disabled={disabled} onChange={event=>onChange(event.target.checked)}/><span className="relative h-7 w-12 shrink-0 rounded-full bg-slate-200 transition peer-checked:bg-teal-700 peer-focus-visible:ring-3 peer-focus-visible:ring-teal-200 after:absolute after:left-1 after:top-1 after:size-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5"/></label>}
function Save({saving,onClick}){return <div className="border-0 pt-5"><button type={onClick?"button":"submit"} onClick={onClick} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white transition hover:bg-teal-800 disabled:opacity-60">{saving?<><FiRefreshCw className="animate-spin"/>Saving...</>:<><FiCheck/>Save Changes</>}</button></div>}
