import { useCallback, useEffect, useMemo, useState } from "react";
import { FiActivity, FiBox, FiBriefcase, FiCheckCircle, FiClock, FiFileText, FiShield, FiTrendingUp, FiUsers } from "react-icons/fi";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import DashboardShell from "../Dashboards/DashboardShell";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";
import { AnalyticsFilters, AnalyticsKpiCard, AnalyticsSkeleton, AnalyticsTable, ChartPanel, EmptyChart } from "../../components/admin/analytics/AnalyticsComponents";

const emptyFilters = () => ({ period: "last_30_days", startDate: "", endDate: "", grouping: "", sellerId: "", companyId: "", categoryId: "", brand: "", productId: "", state: "", district: "" });
const emptyOptions = { sellers: [], companies: [], categories: [], brands: [], products: [], states: [], districts: [] };
const colors = ["#0f766e", "#3b82f6", "#8b5cf6", "#f59e0b", "#22c55e", "#ef4444"];
const number = (value) => Number(value || 0).toLocaleString("en-IN");
const percent = (value) => `${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 1 })}%`;
const duration = (minutes) => { const value = Number(minutes || 0); if (!value) return "—"; if (value < 60) return `${Math.round(value)} min`; if (value < 1440) return `${(value / 60).toFixed(1)} hr`; return `${(value / 1440).toFixed(1)} days`; };
const tooltipStyle = { borderRadius: 12, border: "1px solid #e2e8f0", boxShadow: "0 8px 20px rgba(15,23,42,.08)" };

function SectionHeading({ eyebrow, title, description }) { return <div className="pt-3"><p className="text-xs font-black uppercase tracking-[.16em] text-teal-700">{eyebrow}</p><h2 className="mt-1 text-2xl font-black">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>; }
function BarVisual({ data, dataKey, nameKey, empty }) { return data.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: 18, right: 20 }}><CartesianGrid stroke="#eef0f3" horizontal={false}/><XAxis type="number" allowDecimals={false} axisLine={false} tickLine={false}/><YAxis type="category" dataKey={nameKey} width={105} axisLine={false} tickLine={false} tick={{ fontSize: 11 }}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => number(value)}/><Bar dataKey={dataKey} fill={colors[0]} radius={[0,8,8,0]}/></BarChart></ResponsiveContainer> : <EmptyChart text={empty}/>; }

export default function AnalyticsPage() {
  const { toast } = useToast();
  const [draft, setDraft] = useState(emptyFilters), [applied, setApplied] = useState(emptyFilters), [data, setData] = useState(null), [options, setOptions] = useState(emptyOptions), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = Object.fromEntries(Object.entries(applied).filter(([, value]) => value !== "")); const response = await api.get("/admin/analytics", { params }); setData(response.data); setOptions(response.data.filterOptions || emptyOptions); } catch (requestError) { const message = apiMessage(requestError); setError(message); toast(message, "error"); } finally { setLoading(false); } }, [applied, toast]);
  useEffect(() => { load(); }, [load]);
  const apply = () => { if (draft.period === "custom" && (!draft.startDate || !draft.endDate)) return toast("Select both From and To dates.", "error"); setApplied({ ...draft }); };
  const reset = () => { const initial = emptyFilters(); setDraft(initial); setApplied({ ...initial }); };
  const overviewTrend = useMemo(() => { const map = new Map(); const add = (rows, key, source) => rows.forEach((row) => map.set(row.date, { ...(map.get(row.date) || { date: row.date }), [key]: row[source] })); if (data) { add(data.productAnalytics.trend, "products", "productCount"); add(data.quotationAnalytics.trend, "quotations", "quotationCount"); add(data.customerAnalytics.growth, "customers", "customerCount"); } return [...map.values()].sort((a,b) => a.date.localeCompare(b.date)).map((row) => ({ products: 0, quotations: 0, customers: 0, ...row })); }, [data]);

  return <DashboardShell><div className="mx-auto max-w-[1700px] space-y-6"><div><p className="text-xs font-black uppercase tracking-[.16em] text-teal-700">Business intelligence</p><h1 className="mt-1 text-3xl font-black">Admin Analytics</h1><p className="mt-1 text-sm text-slate-500">Live platform, product, quotation, seller, customer, company and demand insights.</p></div>
    <AnalyticsFilters draft={draft} setDraft={setDraft} options={options} onApply={apply} onReset={reset} loading={loading}/>
    {loading && !data ? <AnalyticsSkeleton/> : error && !data ? <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><p className="font-bold text-red-700">Analytics could not be loaded.</p><p className="mt-1 text-sm text-red-600">{error}</p><button onClick={load} className="mt-4 rounded-xl bg-red-700 px-4 py-2 text-sm font-bold text-white">Try again</button></div> : data && <>
      <SectionHeading eyebrow="Platform overview" title="Live MB Store totals" description={`Updated ${new Date(data.updatedAt).toLocaleString("en-IN")}`}/>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">
        <AnalyticsKpiCard label="Total Companies" value={number(data.overview.totalCompanies)} icon={FiBriefcase}/><AnalyticsKpiCard label="Total Sellers" value={number(data.overview.totalSellers)} icon={FiUsers}/><AnalyticsKpiCard label="Total Customers" value={number(data.overview.totalCustomers)} icon={FiUsers}/><AnalyticsKpiCard label="Total Products" value={number(data.overview.totalProducts)} icon={FiBox}/><AnalyticsKpiCard label="Active Products" value={number(data.overview.activeProducts)} icon={FiCheckCircle}/><AnalyticsKpiCard label="Suspended Products" value={number(data.overview.suspendedProducts)} icon={FiShield} tone="bg-red-50 text-red-700"/><AnalyticsKpiCard label="Total Quotations" value={number(data.overview.totalQuotations)} icon={FiFileText}/><AnalyticsKpiCard label="Pending Quotations" value={number(data.overview.pendingQuotations)} icon={FiClock}/><AnalyticsKpiCard label="Total Enquiries" value={number(data.overview.totalEnquiries)} note="Quotation requests received" icon={FiActivity}/><AnalyticsKpiCard label="Open Enquiries" value={number(data.overview.openEnquiries)} icon={FiClock}/><AnalyticsKpiCard label="Resolved Enquiries" value={number(data.overview.resolvedEnquiries)} icon={FiCheckCircle}/><AnalyticsKpiCard label="Active Sellers" value={number(data.overview.activeSellers)} icon={FiUsers}/><AnalyticsKpiCard label="Pending Approvals" value={number(data.overview.pendingSellerApprovals)} icon={FiClock}/><AnalyticsKpiCard label="New Customers" value={number(data.overview.newCustomers)} note="Selected date range" icon={FiTrendingUp}/>
      </div>

      <ChartPanel title="Growth Overview" subtitle="Products added, new customers and quotation requests in one view"><div className="h-[390px] p-5">{overviewTrend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={overviewTrend}><defs>{colors.slice(0,3).map((color,index)=><linearGradient key={color} id={`overview-${index}`} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={color} stopOpacity={.2}/><stop offset="95%" stopColor={color} stopOpacity={0}/></linearGradient>)}</defs><CartesianGrid stroke="#eef0f3" vertical={false}/><XAxis dataKey="date" minTickGap={25} axisLine={false} tickLine={false} tick={{fontSize:11}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value)=>number(value)}/><Legend iconType="circle"/><Area type="monotone" dataKey="products" name="Products added" stroke={colors[0]} fill="url(#overview-0)" strokeWidth={2.5}/><Area type="monotone" dataKey="customers" name="New customers" stroke={colors[1]} fill="url(#overview-1)" strokeWidth={2.5}/><Area type="monotone" dataKey="quotations" name="Quotation requests" stroke={colors[2]} fill="url(#overview-2)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer> : <EmptyChart text="No growth activity for the selected date range."/>}</div></ChartPanel>

      <SectionHeading eyebrow="Products" title="Product Analytics"/>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7"><AnalyticsKpiCard label="Total Products" value={number(data.productAnalytics.metrics.totalProducts)} icon={FiBox}/><AnalyticsKpiCard label="Active" value={number(data.productAnalytics.metrics.activeProducts)} icon={FiCheckCircle}/><AnalyticsKpiCard label="Suspended" value={number(data.productAnalytics.metrics.suspendedProducts)} icon={FiShield} tone="bg-red-50 text-red-700"/><AnalyticsKpiCard label="Added Today" value={number(data.productAnalytics.metrics.productsAddedToday)} icon={FiTrendingUp}/><AnalyticsKpiCard label="This Month" value={number(data.productAnalytics.metrics.productsAddedThisMonth)} icon={FiTrendingUp}/><AnalyticsKpiCard label="Last Month" value={number(data.productAnalytics.metrics.productsAddedLastMonth)} icon={FiClock}/><AnalyticsKpiCard label="Growth" value={percent(data.productAnalytics.metrics.productGrowthPercentage)} note="Versus previous equal period" icon={FiTrendingUp}/></div>
      <div className="grid gap-6 xl:grid-cols-3"><ChartPanel title="Products Added Over Time"><div className="h-72 p-4">{data.productAnalytics.trend.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={data.productAnalytics.trend}><CartesianGrid stroke="#eef0f3" vertical={false}/><XAxis dataKey="date" minTickGap={22} tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="productCount" name="Products" stroke={colors[0]} strokeWidth={3}/></LineChart></ResponsiveContainer>:<EmptyChart text="No products were added in this period."/>}</div></ChartPanel><ChartPanel title="Products by Category"><div className="h-72 p-4"><BarVisual data={data.productAnalytics.byCategory} dataKey="productCount" nameKey="category" empty="No category data available."/></div></ChartPanel><ChartPanel title="Products by Brand"><div className="h-72 p-4"><BarVisual data={data.productAnalytics.byBrand} dataKey="productCount" nameKey="brand" empty="No brand data available."/></div></ChartPanel></div>

      <SectionHeading eyebrow="Quotations" title="Quotation Analytics"/>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7">{[["Total", "totalQuotations"],["Pending","pendingQuotations"],["Seller Responded","sellerResponded"],["Customer Responded","customerResponded"],["Accepted","accepted"],["Rejected","rejected"],["Declined","declined"]].map(([label,key])=><AnalyticsKpiCard key={key} label={label} value={number(data.quotationAnalytics.metrics[key])} icon={FiFileText}/>)}</div>
      <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><ChartPanel title="Quotation Trend"><div className="h-72 p-4">{data.quotationAnalytics.trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={data.quotationAnalytics.trend}><CartesianGrid stroke="#eef0f3" vertical={false}/><XAxis dataKey="date" minTickGap={24} tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="quotationCount" name="Quotation requests" stroke={colors[2]} fill={colors[2]} fillOpacity={.15} strokeWidth={3}/></AreaChart></ResponsiveContainer>:<EmptyChart text="No quotation data available for the selected date range."/>}</div></ChartPanel><ChartPanel title="Quotation Funnel" subtitle="Mapped to the actual MB Store statuses"><div className="space-y-3 p-5">{[["Total Requests","totalRequests"],["Seller Responded","sellerResponded"],["Customer Responded","customerResponded"],["Accepted","accepted"]].map(([label,key],index)=><div key={key} className="mx-auto rounded-xl bg-teal-50 px-4 py-3 text-center" style={{width:`${100-index*14}%`}}><p className="text-xs font-bold text-teal-700">{label}</p><p className="text-xl font-black text-teal-950">{number(data.quotationAnalytics.funnel[key])}</p></div>)}</div></ChartPanel></div>
      <ChartPanel title="Most Quoted Products" subtitle="Ranked from actual customer quotation requests"><AnalyticsTable rows={data.quotationAnalytics.mostQuotedProducts} columns={[{key:"rank",label:"Rank",render:(_,index)=>`#${index+1}`},{key:"productName",label:"Product"},{key:"brand",label:"Brand"},{key:"category",label:"Category"},{key:"seller",label:"Seller"},{key:"company",label:"Company"},{key:"quotationCount",label:"Requests",align:"right",render:(row)=>number(row.quotationCount)},{key:"totalRequestedUnits",label:"Requested Units",align:"right",render:(row)=>number(row.totalRequestedUnits)}]}/></ChartPanel>

      <SectionHeading eyebrow="Sellers and customers" title="Marketplace Participants"/>
      <div className="grid gap-6 xl:grid-cols-2"><ChartPanel title="Seller Analytics"><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-3">{[["Total","totalSellers"],["Active","activeSellers"],["Inactive","inactiveSellers"],["Pending","pendingApproval"],["New Sellers","newSellers"]].map(([label,key])=><div key={key} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><b className="text-xl">{number(data.sellerAnalytics.metrics[key])}</b></div>)}<div className="rounded-xl bg-teal-50 p-3"><p className="text-xs text-teal-700">Response Rate</p><b className="text-xl text-teal-900">{percent(data.sellerAnalytics.response.responseRate)}</b></div><div className="rounded-xl bg-blue-50 p-3"><p className="text-xs text-blue-700">Avg. Response</p><b className="text-xl text-blue-900">{duration(data.sellerAnalytics.response.averageResponseMinutes)}</b></div></div><AnalyticsTable rows={data.sellerAnalytics.topSellers} columns={[{key:"seller",label:"Seller"},{key:"company",label:"Company"},{key:"quotationCount",label:"Requests",align:"right",render:(row)=>number(row.quotationCount)},{key:"productCount",label:"Quoted Products",align:"right",render:(row)=>number(row.productCount)}]}/></ChartPanel><ChartPanel title="Customer Analytics"><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-3">{[["Total","totalCustomers"],["Active","activeCustomers"],["Inactive","inactiveCustomers"],["New","newCustomers"],["With Quotations","customersWithQuotations"],["With Enquiries","customersWithEnquiries"]].map(([label,key])=><div key={key} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><b className="text-xl">{number(data.customerAnalytics.metrics[key])}</b></div>)}</div><AnalyticsTable rows={data.customerAnalytics.topCustomers} columns={[{key:"customer",label:"Customer"},{key:"customerId",label:"Customer ID"},{key:"quotationCount",label:"Quotations",align:"right",render:(row)=>number(row.quotationCount)},{key:"enquiryCount",label:"Enquiries",align:"right",render:(row)=>number(row.enquiryCount)}]}/></ChartPanel></div>

      <SectionHeading eyebrow="Demand and location" title="Customer Demand" description="Demand is calculated from customer quotation requests, not product inventory."/>
      <div className="grid gap-6 xl:grid-cols-3"><ChartPanel title="Most Requested Categories"><div className="h-72 p-4"><BarVisual data={data.demandAnalytics.mostRequestedCategories} dataKey="quotationCount" nameKey="category" empty="No category demand data."/></div></ChartPanel><ChartPanel title="Most Requested Brands"><div className="h-72 p-4"><BarVisual data={data.demandAnalytics.mostRequestedBrands} dataKey="quotationCount" nameKey="brand" empty="No brand demand data."/></div></ChartPanel><ChartPanel title="Quotation Demand by State"><div className="h-72 p-4"><BarVisual data={data.locationAnalytics.demandByState} dataKey="quotationCount" nameKey="state" empty="No state demand data."/></div></ChartPanel></div>
      <div className="grid gap-6 xl:grid-cols-2"><ChartPanel title="Customers by State"><AnalyticsTable rows={data.locationAnalytics.customersByState} columns={[{key:"state",label:"State"},{key:"customerCount",label:"Customers",align:"right",render:(row)=>number(row.customerCount)}]}/></ChartPanel><ChartPanel title="Quotation Demand by District"><AnalyticsTable rows={data.locationAnalytics.demandByDistrict} columns={[{key:"district",label:"District"},{key:"state",label:"State"},{key:"quotationCount",label:"Requests",align:"right",render:(row)=>number(row.quotationCount)}]}/></ChartPanel></div>

      <SectionHeading eyebrow="Companies" title="Company Performance"/>
      <ChartPanel title="Company Performance" subtitle="Quotation count represents seller responses; enquiries represent customer requests."><AnalyticsTable rows={data.companyAnalytics.performance} columns={[{key:"company",label:"Company"},{key:"sellerCount",label:"Sellers",align:"right",render:(row)=>number(row.sellerCount)},{key:"productCount",label:"Products",align:"right",render:(row)=>number(row.productCount)},{key:"quotationCount",label:"Quotations",align:"right",render:(row)=>number(row.quotationCount)},{key:"enquiryCount",label:"Enquiries",align:"right",render:(row)=>number(row.enquiryCount)}]}/></ChartPanel>
    </>}
  </div></DashboardShell>;
}
