import { useCallback, useEffect, useRef, useState } from "react";
import { FiChevronLeft, FiChevronRight, FiImage, FiPlus, FiSearch, FiTrash2, FiUpload, FiX } from "react-icons/fi";
import { motion } from "framer-motion";
import DashboardShell from "../Dashboards/DashboardShell";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";

const MAX_LOGO_BYTES=200*1024, acceptedTypes=new Set(["image/png","image/jpeg","image/webp"]);
function validateName(value){const name=value.trim();if(!name)return "Company name is required.";if(name.length<2||name.length>160)return "Company name must be between 2 and 160 characters.";if(!/^[\p{L}\p{N}&.,'()\- ]+$/u.test(name))return "Company name contains unsupported characters.";return ""}
function validateFile(file){if(!file)return "Company logo is required.";if(!acceptedTypes.has(file.type))return "Logo must be a PNG, JPEG, or WebP image.";if(file.size>=MAX_LOGO_BYTES)return "Logo must be less than 200 KB.";return ""}

export default function CompanyManagement(){
  const {toast}=useToast(), inputRef=useRef(null); const [companies,setCompanies]=useState([]),[meta,setMeta]=useState({totalRecords:0,totalPages:1}),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[name,setName]=useState(""),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1)},300);return()=>clearTimeout(timer)},[search]);
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await api.get("/admin/companies",{params:{search:query||undefined,page,limit:20}});setCompanies(data.data);setMeta(data)}catch(error){toast(apiMessage(error),"error")}finally{setLoading(false)}},[query,page,toast]); useEffect(()=>{load()},[load]);
  const reset=()=>{setOpen(false);setName("");setFile(null);setPreview("");setErrors({});if(inputRef.current)inputRef.current.value=""};
  const selectFile=event=>{const selected=event.target.files?.[0]||null,error=validateFile(selected);setFile(selected);setErrors(current=>({...current,logo:error}));if(preview)URL.revokeObjectURL(preview);setPreview(!error&&selected?URL.createObjectURL(selected):"")};
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const submit=async event=>{event.preventDefault();const nextErrors={name:validateName(name),logo:validateFile(file)};setErrors(nextErrors);if(Object.values(nextErrors).some(Boolean))return;setSaving(true);try{const logoData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await api.post("/admin/companies",{companyName:name.trim(),logoName:file.name,logoData});toast("Company added successfully.");reset();setPage(1);await load()}catch(error){toast(apiMessage(error),"error")}finally{setSaving(false)}};
  const remove=async company=>{if(!window.confirm(`Delete ${company.companyName}?`))return;try{await api.delete(`/admin/companies/${company.id}`);toast("Company deleted successfully.");await load()}catch(error){toast(apiMessage(error),"error")}};
  return <DashboardShell><div className="mx-auto w-full max-w-[1700px]"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-teal-700">Admin management</p><h1 className="mt-1 text-3xl font-black">Company Management</h1><p className="mt-1 text-sm text-slate-500">Manage companies and their marketplace logos.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white shadow-sm hover:bg-teal-800"><FiPlus/>Add Company</button></div>
  <div className="mb-4 grid gap-4 md:grid-cols-[220px_minmax(0,1fr)]"><div className="rounded-2xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Total Companies</p><strong className="mt-1 block text-3xl text-slate-900">{meta.totalRecords}</strong></div><label className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-5 shadow-sm"><FiSearch className="text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} className="w-full py-4 text-sm outline-none" placeholder="Search by company name or MBSCO ID..."/></label></div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-175 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Company ID</th><th className="px-5 py-3">Logo</th><th className="px-5 py-3">Company Name</th><th className="px-5 py-3">Logo Filename</th><th className="px-5 py-3">Created</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?Array.from({length:5},(_,index)=><tr key={index}>{Array.from({length:6},(_,cell)=><td key={cell} className="px-5 py-4"><div className="h-5 animate-pulse rounded bg-slate-200"/></td>)}</tr>):companies.length===0?<tr><td colSpan="6" className="py-16 text-center"><FiImage className="mx-auto text-4xl text-slate-300"/><p className="mt-3 font-bold text-slate-600">{query?"No companies match your search.":"No companies found."}</p></td></tr>:companies.map(company=><tr key={company.id} className="hover:bg-slate-50"><td className="px-5 py-3 font-mono font-bold text-teal-700">{company.companyId}</td><td className="px-5 py-2"><div className="grid size-12 place-items-center overflow-hidden rounded-xl border border-slate-200 bg-white"><img src={`${api.defaults.baseURL}${company.logoUrl}`} alt={`${company.companyName} logo`} className="max-h-full max-w-full object-contain"/></div></td><td className="px-5 font-bold">{company.companyName}</td><td className="px-5 text-slate-500">{company.logoName}</td><td className="px-5 text-slate-500">{new Date(company.createdAt).toLocaleDateString()}</td><td className="px-5 text-right"><button onClick={()=>remove(company)} title="Delete company" className="rounded-lg border border-red-200 p-2 text-red-600 hover:bg-red-50"><FiTrash2/></button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 p-4"><p className="text-sm text-slate-500">Page {page} of {meta.totalPages}</p><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronLeft/></button><button disabled={page>=meta.totalPages} onClick={()=>setPage(value=>value+1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronRight/></button></div></div></section></div>
  {open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><motion.div initial={{opacity:0,scale:.97,y:12}} animate={{opacity:1,scale:1,y:0}} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Add Company</h2><p className="mt-1 text-sm text-slate-500">The company ID is generated automatically.</p></div><button onClick={reset} className="grid size-10 place-items-center rounded-xl bg-slate-100"><FiX/></button></div><form onSubmit={submit} className="mt-6 space-y-5"><label className="block text-sm font-bold text-slate-700">Company Name<input value={name} onChange={event=>{setName(event.target.value);setErrors(current=>({...current,name:validateName(event.target.value)}))}} onBlur={()=>setErrors(current=>({...current,name:validateName(name)}))} className={`mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:ring-4 ${errors.name?"border-red-400 focus:ring-red-100":"border-slate-200 focus:border-teal-600 focus:ring-teal-100"}`} placeholder="Enter company name"/>{errors.name&&<span className="mt-1.5 block text-xs text-red-600">{errors.name}</span>}</label><div><p className="text-sm font-bold text-slate-700">Company Logo</p><button type="button" onClick={()=>inputRef.current?.click()} className={`mt-2 grid min-h-40 w-full place-items-center overflow-hidden rounded-2xl border-2 border-dashed p-4 ${errors.logo?"border-red-400 bg-red-50/30":"border-slate-300 hover:border-teal-500"}`}>{preview?<img src={preview} alt="Logo preview" className="max-h-32 max-w-full object-contain"/>:<span className="text-center text-slate-500"><FiUpload className="mx-auto text-3xl"/><b className="mt-2 block">Choose logo</b><small>PNG, JPEG or WebP · less than 200 KB</small></span>}</button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={selectFile} className="hidden"/>{file&&!errors.logo&&<p className="mt-2 text-xs text-slate-500">{file.name} · {(file.size/1024).toFixed(1)} KB</p>}{errors.logo&&<span className="mt-1.5 block text-xs text-red-600">{errors.logo}</span>}</div><div className="flex justify-end gap-3"><button type="button" onClick={reset} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Cancel</button><button disabled={saving||Boolean(errors.name)||Boolean(errors.logo)} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Adding...":"Add Company"}</button></div></form></motion.div></div>}</DashboardShell>;
}
