import { useCallback,useEffect,useState } from "react";
import { FiChevronLeft,FiChevronRight,FiEdit2,FiEye,FiPlus,FiSearch,FiTrash2,FiUsers,FiX } from "react-icons/fi";
import api,{apiMessage} from "../../lib/api";
import {useToast} from "../../context/ToastContext";
import DashboardShell from "../Dashboards/DashboardShell";

const sellerColumns=[["sellerId","Seller ID"],["sellerName","Seller Name"],["companyName","Company"],["email","Email"],["phoneNumber","Phone"],["gst","GST"],["state","State"],["verificationStatus","Verification"]];
const customerColumns=[["customerId","Customer ID"],["customerName","Customer Name"],["email","Email"],["phoneNumber","Phone"],["address","Address"],["state","State"],["district","District"],["area","Area"],["landmark","Landmark"]];
const blankSeller={sellerName:"",email:"",password:"",companyName:"",gst:"",phoneNumber:"",businessEmail:"",address:"",state:"",district:"",area:"",landmark:"",website:""};
const tone=value=>value==="Verified"?"bg-emerald-50 text-emerald-700":value==="Rejected"||value==="Inactive"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700";

export default function ProfileManagement({type}){
  const seller=type==="sellers",columns=seller?sellerColumns:customerColumns,{toast}=useToast();
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[completion,setCompletion]=useState(""),[sort,setSort]=useState("newest"),[page,setPage]=useState(1),[meta,setMeta]=useState({totalPages:1,totalRecords:0});
  const [view,setView]=useState(null),[form,setForm]=useState(null),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(1)},350);return()=>clearTimeout(timer)},[search]);
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await api.get(`/admin/${type}`,{params:{search:query||undefined,status:status||undefined,completion:completion||undefined,sort,page,limit:20}});setRows(data.data);setMeta(data)}catch(error){toast(apiMessage(error),"error")}finally{setLoading(false)}},[type,query,status,completion,sort,page,toast]);useEffect(()=>{load()},[load]);
  const change=setter=>event=>{setter(event.target.value);setPage(1)};
  const openView=async row=>{try{if(seller){const {data}=await api.get(`/admin/sellers/${row.userId}`);setView(data.seller)}else setView(row)}catch(error){toast(apiMessage(error),"error")}};
  const openEdit=async row=>{try{const {data}=await api.get(`/admin/sellers/${row.userId}`);setForm({...blankSeller,...data.seller,password:""});setErrors({})}catch(error){toast(apiMessage(error),"error")}};
  const validate=()=>{const next={};if(form.sellerName.trim().length<2)next.sellerName="Enter a seller name.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email="Enter a valid email.";if(!form.userId&&form.password.length<8)next.password="Password must contain at least 8 characters.";if(form.companyName.trim().length<2)next.companyName="Enter a company name.";if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/i.test(form.gst))next.gst="Enter a valid GST number.";setErrors(next);return !Object.keys(next).length};
  const save=async event=>{event.preventDefault();if(!validate())return;setBusy(true);try{const payload=Object.fromEntries(Object.entries(form).filter(([key])=>!['id','userId','sellerId','status','verificationStatus','profileCompletion','createdAt','updatedAt','isComplete','missingFields'].includes(key)));if(form.userId)await api.put(`/admin/sellers/${form.userId}`,payload);else await api.post("/admin/sellers",payload);toast(form.userId?"Seller updated successfully.":"Seller created successfully.");setForm(null);load()}catch(error){toast(apiMessage(error),"error")}finally{setBusy(false)}};
  const toggle=async row=>{const activate=row.status!=="Verified";if(!window.confirm(`${activate?"Activate":"Deactivate"} ${row.sellerName}?`))return;try{await api.patch(`/admin/sellers/${row.userId}/status`,{status:activate?"Verified":"Inactive"});toast(`Seller ${activate?"activated":"deactivated"} successfully.`);load()}catch(error){toast(apiMessage(error),"error")}};
  const remove=async row=>{if(!window.confirm(`Remove access for ${row.sellerName}? Existing products and records will be preserved.`))return;try{await api.delete(`/admin/sellers/${row.userId}`);toast("Seller access removed successfully.");load()}catch(error){toast(apiMessage(error),"error")}};

  return <DashboardShell><div className="mx-auto max-w-[1700px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-teal-700">Admin management</p><h1 className="mt-1 text-3xl font-black">{seller?"Seller":"Customer"} Management</h1><p className="mt-1 text-sm text-slate-500">{meta.totalRecords} record{meta.totalRecords===1?"":"s"}</p></div>{seller&&<button onClick={()=>{setForm({...blankSeller});setErrors({})}} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/>Create Seller</button>}</div>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><label className="flex min-w-64 flex-1 items-center gap-2 rounded-xl border px-4 py-2.5"><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full text-sm outline-none" placeholder={`Search ${type} by name, ID, email or phone...`}/></label><select value={status} onChange={change(setStatus)} className="rounded-xl border px-3 text-sm"><option value="">All statuses</option>{["Verified","Pending","Rejected","Inactive"].map(x=><option key={x}>{x}</option>)}</select><select value={completion} onChange={change(setCompletion)} className="rounded-xl border px-3 text-sm"><option value="">All profiles</option><option value="completed">Completed</option><option value="incomplete">Incomplete</option></select><select value={sort} onChange={change(setSort)} className="rounded-xl border px-3 text-sm"><option value="newest">Newest</option><option value="oldest">Oldest</option></select></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{columns.map(([,label])=><th key={label} className="px-4 py-3">{label}</th>)}<th className="px-4">Completion</th><th className="px-4">Status</th><th className="px-4">Created</th><th className="px-4">Actions</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={columns.length+4} className="p-12 text-center">Loading...</td></tr>:rows.length===0?<tr><td colSpan={columns.length+4} className="py-16 text-center"><FiUsers className="mx-auto text-3xl text-slate-300"/><p className="mt-3 font-bold">No {type} found.</p></td></tr>:rows.map(row=><tr key={row.id} className="hover:bg-slate-50">{columns.map(([key])=><td key={key} className="max-w-52 truncate px-4 py-4" title={row[key]||""}>{row[key]||"—"}</td>)}<td className="px-4"><b>{row.profileCompletion}%</b></td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tone(row.status)}`}>{row.status}</span></td><td className="whitespace-nowrap px-4">{new Date(row.createdAt).toLocaleDateString()}</td><td className="px-4"><div className="flex gap-2"><Action title="View" onClick={()=>openView(row)}><FiEye/></Action>{seller&&<><Action title="Edit" onClick={()=>openEdit(row)} color="text-blue-600"><FiEdit2/></Action><Action title={row.status==="Verified"?"Deactivate":"Activate"} onClick={()=>toggle(row)} color={row.status==="Verified"?"text-amber-600":"text-emerald-600"}><FiUsers/></Action><Action title="Remove access" onClick={()=>remove(row)} color="text-red-600"><FiTrash2/></Action></>}</div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-4"><p className="text-sm text-slate-500">Page {page} of {meta.totalPages}</p><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronLeft/></button><button disabled={page>=meta.totalPages} onClick={()=>setPage(x=>x+1)} className="rounded-lg border p-2 disabled:opacity-40"><FiChevronRight/></button></div></div></section></div>
  {view&&<Modal title="Seller details" close={()=>setView(null)}><div className="mt-5 grid gap-4 sm:grid-cols-2">{sellerColumns.concat([["status","Account Status"],["address","Address"],["website","Website"]]).map(([key,label])=><div key={key} className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold uppercase text-slate-400">{label}</span><p className="mt-1 break-words font-semibold">{view[key]||"—"}</p></div>)}</div></Modal>}
  {form&&<Modal title={form.userId?"Edit seller":"Create seller"} close={()=>setForm(null)}><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Seller name" value={form.sellerName} onChange={value=>setForm({...form,sellerName:value})} error={errors.sellerName}/><Input label="Email" type="email" value={form.email} onChange={value=>setForm({...form,email:value})} error={errors.email}/>{!form.userId&&<Input label="Password" type="password" value={form.password} onChange={value=>setForm({...form,password:value})} error={errors.password}/>}<Input label="Company name" value={form.companyName} onChange={value=>setForm({...form,companyName:value})} error={errors.companyName}/><Input label="GST number" value={form.gst} onChange={value=>setForm({...form,gst:value.toUpperCase()})} error={errors.gst}/><Input label="Phone" value={form.phoneNumber||""} onChange={value=>setForm({...form,phoneNumber:value})}/><Input label="Business email" type="email" value={form.businessEmail||""} onChange={value=>setForm({...form,businessEmail:value})}/><Input label="Website" value={form.website||""} onChange={value=>setForm({...form,website:value})}/><Input label="Address" value={form.address||""} onChange={value=>setForm({...form,address:value})}/><Input label="State" value={form.state||""} onChange={value=>setForm({...form,state:value})}/><Input label="District" value={form.district||""} onChange={value=>setForm({...form,district:value})}/><div className="flex items-end gap-3 sm:col-span-2"><button type="button" onClick={()=>setForm(null)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button disabled={busy} className="rounded-xl bg-teal-700 px-6 py-3 font-bold text-white disabled:opacity-50">{busy?"Saving...":"Save seller"}</button></div></form></Modal>}
  </DashboardShell>;
}
function Action({title,color="",children,...props}){return <button title={title} aria-label={title} className={`rounded-lg border p-2 ${color}`} {...props}>{children}</button>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/55 p-4"><section className="my-6 w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}><FiX/></button></div>{children}</section></div>}
function Input({label,error,onChange,...props}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><input {...props} onChange={event=>onChange(event.target.value)} className={`w-full rounded-xl border px-4 py-3 outline-none focus:ring-4 focus:ring-teal-100 ${error?"border-red-400":"border-slate-200"}`}/>{error&&<span className="mt-1 block text-sm text-red-600">{error}</span>}</label>}
