import { useCallback, useEffect, useState } from "react";
import { FiAlertTriangle,FiCheckCircle,FiClock,FiEdit2,FiInbox,FiPlus,FiSearch,FiUsers,FiX } from "react-icons/fi";
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip} from "recharts";
import DashboardShell from "../Dashboards/DashboardShell";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";

const empty={name:"",email:"",gender:"",password:"",confirmPassword:""};
export default function SupportManagement(){
  const {toast}=useToast(); const [rows,setRows]=useState([]); const [analytics,setAnalytics]=useState(null); const [pagination,setPagination]=useState({page:1,total:0,totalPages:1}); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [form,setForm]=useState(null); const [errors,setErrors]=useState({}); const [busy,setBusy]=useState(false);
  const load=useCallback(async(page=1)=>{try{const {data}=await api.get("/admin/support",{params:{page,limit:10,search:search||undefined,status:status||undefined}});setRows(data.data);setPagination(data.pagination)}catch(error){toast(apiMessage(error),"error")}},[search,status,toast]);
  useEffect(()=>{const timer=setTimeout(()=>load(1),300);return()=>clearTimeout(timer)},[load]);
  useEffect(()=>{api.get('/admin/support-analytics').then(({data})=>setAnalytics(data)).catch(error=>toast(apiMessage(error),'error'))},[toast]);
  const validate=()=>{const next={};const name=form.name.trim();const email=form.email.trim();if(name.length<2)next.name="Enter at least 2 characters.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email="Enter a valid email address.";if(!form.gender)next.gender="Gender is required.";setErrors(next);return !Object.keys(next).length};
  const save=async(event)=>{event.preventDefault();if(!validate())return;setBusy(true);try{const payload={name:form.name.trim(),email:form.email.trim().toLowerCase(),gender:form.gender};if(form.id)await api.put(`/admin/support/${form.id}`,payload);else await api.post("/admin/support",payload);toast(form.id?"Support user updated successfully.":"Support user created successfully.");setForm(null);load(pagination.page)}catch(error){const message=apiMessage(error);if(error.response?.status===409)setErrors({email:"An account with this email already exists."});toast(message,"error")}finally{setBusy(false)}};
  const toggle=async(row)=>{const action=row.status==="active"?"deactivate":"activate";if(!window.confirm(`${action[0].toUpperCase()+action.slice(1)} this support account?`))return;try{await api.patch(`/admin/support/${row.id}/status`,{status:row.status==="active"?"inactive":"active"});toast(`Support user ${action}d successfully.`);load(pagination.page)}catch(error){toast(apiMessage(error),"error")}};
  return <><DashboardShell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-teal-700">Support Management</p><h1 className="mt-2 text-3xl font-black">Support Operations</h1><p className="mt-2 text-slate-500">Monitor customer issues, agent performance, workload and resolution health.</p></div><button onClick={()=>{setForm({...empty});setErrors({})}} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/>Create Support</button></div>
  <SupportAnalytics data={analytics}/>
  <div className="mt-8"><h2 className="text-2xl font-black">Support Team</h2><p className="mt-1 text-sm text-slate-500">Manage agent accounts and access.</p></div>
  <section className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><label className="flex min-w-64 flex-1 items-center gap-3 rounded-xl border border-slate-200 px-4"><FiSearch className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search support users..." className="w-full py-3 outline-none"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{["Name","Email","Gender","Role","Status","Created Date","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.length?rows.map(row=><tr key={row.id}><td className="px-5 py-4 font-bold">{row.name}</td><td className="px-5 py-4 text-slate-600">{row.email}</td><td className="px-5 py-4">{row.gender}</td><td className="px-5 py-4">{row.role}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${row.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{row.status}</span></td><td className="px-5 py-4 text-slate-500">{new Date(row.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><div className="flex gap-2"><button title="Edit" onClick={()=>{setForm({...row});setErrors({})}} className="rounded-lg border p-2 text-teal-700"><FiEdit2/></button><button onClick={()=>toggle(row)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">{row.status==="active"?"Deactivate":"Activate"}</button></div></td></tr>):<tr><td colSpan="7" className="p-10 text-center text-slate-400">No support users found.</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t p-4 text-sm text-slate-500"><span>Showing {pagination.total?((pagination.page-1)*10)+1:0}-{Math.min(pagination.page*10,pagination.total)} of {pagination.total}</span><div className="flex gap-2"><button disabled={pagination.page<=1} onClick={()=>load(pagination.page-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={pagination.page>=pagination.totalPages} onClick={()=>load(pagination.page+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div></section></DashboardShell>
  {form&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{form.id?"Edit Support User":"Create Support User"}</h2><button type="button" onClick={()=>setForm(null)}><FiX/></button></div><div className="mt-6 space-y-4"><Field label="Full Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} error={errors.name}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} error={errors.email}/><label className="block"><span className="mb-2 block text-sm font-bold">Gender</span><select value={form.gender||""} onChange={e=>setForm({...form,gender:e.target.value})} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">Select Gender</option><option>Male</option><option>Female</option><option>Other</option></select>{errors.gender&&<span className="mt-1 block text-sm text-red-600">{errors.gender}</span>}</label></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={()=>setForm(null)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button disabled={busy} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white disabled:opacity-50">{form.id?"Save Changes":"Create Support"}</button></div></form></div>}
  </>;
}
function Field({label,error,...props}){return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><input {...props} className={`w-full rounded-xl border px-4 py-3 outline-none focus:ring-4 focus:ring-teal-100 ${error?"border-red-400":"border-slate-200"}`}/>{error&&<span className="mt-1 block text-sm text-red-600">{error}</span>}</label>}

const colors=['#0f766e','#2563eb','#f59e0b','#ef4444','#8b5cf6','#64748b'];
const duration=value=>!value?'—':value<60?`${Math.round(value)}m`:`${Math.floor(value/60)}h ${Math.round(value%60)}m`;
function SupportAnalytics({data}){
  if(!data)return <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-36 animate-pulse rounded-2xl bg-slate-200"/>)}</div>;
  const s=data.summary||{},cards=[['Total Issues',s.totalIssues,FiInbox],['Open Issues',s.openIssues,FiAlertTriangle],['Resolved Issues',s.resolvedIssues,FiCheckCircle],['Unassigned',s.unassignedIssues,FiUsers],['Urgent Issues',s.urgentIssues,FiAlertTriangle],['Customers Affected',s.affectedCustomers,FiUsers],['Avg First Response',duration(s.avgFirstResponseMinutes),FiClock],['Avg Resolution',duration(s.avgResolutionMinutes),FiClock]];
  return <div className="mt-7 space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon/></span><strong className="mt-4 block text-3xl">{value??0}</strong><p className="mt-1 text-sm text-slate-500">{label}</p></article>)}</div>
  <div className="grid gap-5 xl:grid-cols-2"><Chart title="Issues by Category" rows={data.categories}/><Chart title="Issues by Priority" rows={data.priorities}/></div>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">Support Agent Analytics</h2><p className="mt-1 text-sm text-slate-500">Compare current workload, urgent cases and response performance.</p></div><div className="overflow-x-auto"><table className="w-full min-w-240 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{['Support Agent','Support ID','Status','Assigned','Open','Resolved','Urgent','Avg Response','Avg Resolution','Last Activity'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{data.agents.map(a=><tr key={a.id}><td className="px-4 py-4"><b>{a.name}</b><span className="block text-xs text-slate-400">{a.email}</span></td><td className="px-4 font-mono text-xs">{a.supportId||'—'}</td><td className="px-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${a.status==='Verified'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{a.status}</span></td><td className="px-4 font-bold">{a.totalAssigned}</td><td className="px-4 text-amber-700">{a.openTickets}</td><td className="px-4 text-emerald-700">{a.resolvedTickets}</td><td className="px-4 text-red-700">{a.urgentTickets}</td><td className="px-4">{duration(a.avgFirstResponseMinutes)}</td><td className="px-4">{duration(a.avgResolutionMinutes)}</td><td className="px-4 text-slate-500">{a.lastActivity?new Date(a.lastActivity).toLocaleDateString():'No activity'}</td></tr>)}</tbody></table></div></section>
  <div className="grid gap-5 xl:grid-cols-2"><SimpleTable title="Customers Raising Support Issues" headers={['Customer','Total','Open','Latest Issue','Last Activity']} rows={data.customers.map(c=>[<span><b>{c.customerName}</b><small className="block text-slate-400">{c.customerId} · {c.email}</small></span>,c.totalIssues,c.openIssues,c.latestIssue,c.lastActivity?new Date(c.lastActivity).toLocaleDateString():'—'])}/><SimpleTable title="Recent Support Issues" headers={['Ticket','Customer / Seller','Issue','Related','Status']} rows={data.recentIssues.map(r=>[r.ticketNumber,r.customerName||r.sellerCompany||r.sellerName||'Platform user',<span><b>{r.subject}</b><small className="block text-slate-400">{r.category} · {r.priority}</small></span>,r.quotationNumber||r.productName||'General issue',r.status])}/></div></div>;
}
function Chart({title,rows=[]}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">{title}</h2><div className="mt-3 h-64"><ResponsiveContainer><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={50} outerRadius={85}>{rows.map((x,i)=><Cell key={x.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="flex flex-wrap gap-2">{rows.map((x,i)=><span key={x.name} className="rounded-full bg-slate-50 px-3 py-1 text-xs font-bold"><i className="mr-1.5 inline-block size-2 rounded-full" style={{background:colors[i%colors.length]}}/>{x.name}: {x.value}</span>)}</div></section>}
function SimpleTable({title,headers,rows}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><h2 className="border-b p-5 text-lg font-black">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{headers.map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j} className="px-4 py-4">{value??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-slate-400">No support activity yet.</p>}</div></section>}
