const router = require("express").Router();
const { param, body } = require("express-validator");
const controller = require("../controllers/admin.controller");
const analyticsController = require("../controllers/admin-analytics.controller");
const companyController = require("../controllers/company.controller");
const categoryController = require("../controllers/category.controller");
const categoryImageController = require("../controllers/category-image.controller");
const supportController = require("../controllers/support.controller");
const bannerController = require("../controllers/banner.controller");
const asyncHandler = require("../utils/async-handler");
const validate = require("../middleware/validate.middleware");
const { authMiddleware, adminMiddleware } = require("../middleware/auth.middleware");
router.use(authMiddleware, adminMiddleware);
router.get("/dashboard", asyncHandler(controller.dashboard));
router.get("/analytics", asyncHandler(analyticsController.get));
router.get("/seller-requests", asyncHandler(controller.requests));
router.get("/sellers", asyncHandler(controller.sellers));
router.post("/sellers", asyncHandler(controller.createSeller));
router.get("/sellers/:id", param("id").isInt({min:1}), validate, asyncHandler(controller.seller));
router.put("/sellers/:id", param("id").isInt({min:1}), validate, asyncHandler(controller.updateSeller));
router.patch("/sellers/:id/status", [param("id").isInt({min:1}),body("status").isIn(["Verified","Inactive"])], validate, asyncHandler(controller.sellerStatus));
router.delete("/sellers/:id", param("id").isInt({min:1}), validate, asyncHandler(controller.removeSeller));
router.get("/customers", asyncHandler(controller.customers));
router.get("/products", asyncHandler(controller.products));
router.get("/product-reports", asyncHandler(controller.productReports));
router.patch("/product-reports/:id/status", [param("id").isInt({min:1}), body("status").isIn(["actioned","dismissed"]), body("note").optional().trim().isLength({max:500})], validate, asyncHandler(controller.productReportStatus));
router.patch("/products/:id/status", [param("id").isInt({min:1}), body("status").isIn(["suspended","active"]), body("reason").optional().trim().isLength({max:500}), body("reportId").optional().isInt({min:1})], validate, asyncHandler(controller.productStatus));
router.get("/support", asyncHandler(supportController.list));
router.get("/support-analytics", asyncHandler(supportController.analytics));
router.post("/support", supportController.validation, validate, asyncHandler(supportController.create));
router.get("/support/:id", param("id").isInt({min:1}), validate, asyncHandler(supportController.one));
router.put("/support/:id", [param("id").isInt({min:1}), ...supportController.validation], validate, asyncHandler(supportController.update));
router.patch("/support/:id/status", [param("id").isInt({min:1}), body("status").isIn(["active", "inactive"])], validate, asyncHandler(supportController.status));
router.get("/companies", asyncHandler(companyController.list));
router.post("/companies", asyncHandler(companyController.create));
router.get("/companies/:id/logo", param("id").isInt({min:1}), validate, asyncHandler(companyController.logo));
router.delete("/companies/:id", param("id").isInt({min:1}), validate, asyncHandler(companyController.remove));
router.get("/categories", asyncHandler(categoryController.list));
router.get("/banners", asyncHandler(bannerController.list));
router.post("/banners", asyncHandler(bannerController.create));
router.put("/banners/:id", param("id").isInt({min:1}), validate, asyncHandler(bannerController.update));
router.patch("/banners/:id/status", [param("id").isInt({min:1}),body("status").isIn(["active","inactive"])], validate, asyncHandler(bannerController.status));
router.delete("/banners/:id", param("id").isInt({min:1}), validate, asyncHandler(bannerController.remove));
router.get("/categories/options", asyncHandler(categoryController.options));
router.post("/categories", asyncHandler(categoryController.create));
router.get("/categories/:id", param("id").isInt({min:1}), validate, asyncHandler(categoryController.one));
router.put("/categories/:id", param("id").isInt({min:1}), validate, asyncHandler(categoryController.update));
router.patch("/categories/:id/status", param("id").isInt({min:1}), validate, asyncHandler(categoryController.status));
router.put("/categories/:id/image", param("id").isInt({min:1}), validate, asyncHandler(categoryImageController.update));
router.delete("/categories/:id", param("id").isInt({min:1}), validate, asyncHandler(categoryController.remove));
router.put("/approve/:id", param("id").isInt({ min: 1 }), validate, asyncHandler(controller.approve));
router.put("/reject/:id", [param("id").isInt({ min: 1 }), body("reason").optional().trim().isLength({ max: 500 })], validate, asyncHandler(controller.reject));
module.exports = router;
