const router = require("express").Router();
const controller = require("../controllers/auth.controller");
const asyncHandler = require("../utils/async-handler");
const validate = require("../middleware/validate.middleware");
const rules = require("../validators/auth.validators");
const { optionalAuthMiddleware } = require("../middleware/auth.middleware");
router.post("/register", rules.registerRules, validate, asyncHandler(controller.register));
router.post("/register/seller", rules.sellerRules, validate, asyncHandler(controller.registerSeller));
router.post("/login", rules.loginRules, validate, asyncHandler(controller.login));
router.post("/refresh", asyncHandler(controller.refresh));
router.post("/forgot-password", rules.forgotPasswordRules, validate, asyncHandler(controller.forgotPassword));
router.post("/reset-password", rules.resetPasswordRules, validate, asyncHandler(controller.resetPassword));
router.post("/logout", asyncHandler(controller.logout));
router.get("/me", optionalAuthMiddleware, asyncHandler(controller.me));
module.exports = router;
