const router=require("express").Router();
const controller=require("../controllers/support-ticket.controller");
const asyncHandler=require("../utils/async-handler");
const {authMiddleware}=require("../middleware/auth.middleware");
const ApiError=require("../utils/api-error");
router.use(authMiddleware,(req,_res,next)=>['Support','Admin'].includes(req.user.role)?next():next(new ApiError(403,'Unauthorized.','UNAUTHORIZED')));
router.get("/dashboard",asyncHandler(controller.dashboard));
router.get("/agents",asyncHandler(controller.agents));
router.get("/tickets",asyncHandler(controller.list));
router.post("/tickets",asyncHandler(controller.create));
router.get("/tickets/:id",asyncHandler(controller.detail));
router.put("/tickets/:id",asyncHandler(controller.update));
router.post("/tickets/:id/assign",asyncHandler(controller.assign));
router.post("/tickets/:id/messages",asyncHandler(controller.message));
router.post("/tickets/:id/internal-notes",asyncHandler(controller.note));
router.post("/tickets/:id/forward-to-:target",asyncHandler(controller.forward));
router.post("/tickets/:id/resolve",(req,_res,next)=>{req.body.status='Resolved';next()},asyncHandler(controller.update));
router.post("/tickets/:id/close",(req,_res,next)=>{req.body.status='Closed';next()},asyncHandler(controller.update));
router.get("/customers",asyncHandler(controller.customers));
router.get("/sellers",asyncHandler(controller.sellers));
router.get("/quotations",asyncHandler(controller.quotations));
router.get("/follow-ups",asyncHandler(controller.followUps));
router.post("/follow-ups",asyncHandler(controller.createFollowUp));
router.put("/follow-ups/:id",asyncHandler(controller.updateFollowUp));
router.get("/notifications",asyncHandler(controller.notifications));
router.put("/notifications/:id/read",asyncHandler(controller.readNotification));
router.get("/profile",asyncHandler(controller.profile));
router.put("/profile",asyncHandler(controller.updateProfile));
module.exports=router;
