import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { FiArrowLeft, FiBriefcase, FiLoader, FiMail, FiShoppingBag, FiUser } from "react-icons/fi";
import { Link, useLocation, useNavigate } from "react-router-dom";
import api, { apiMessage } from "../../lib/api";
import { useAuth } from "../../context/AuthContext";
import { useToast } from "../../context/ToastContext";
import Modal from "../../components/Auth/Modal";

export default function AuthPage({ mode }) {
  const isRegister = mode === "register"; const navigate = useNavigate(); const location = useLocation(); const { setUser } = useAuth(); const { toast } = useToast();
  const [step, setStep] = useState("email"); const [busy, setBusy] = useState(false); const [identity, setIdentity] = useState(null); const [otp, setOtp] = useState(Array(6).fill("")); const [expires, setExpires] = useState(0); const [resend, setResend] = useState(0); const [registrationToken, setRegistrationToken] = useState(""); const [success, setSuccess] = useState(false); const [duplicateEmail, setDuplicateEmail] = useState("");
  const otpRefs = useRef([]); const { register, handleSubmit, setError, clearErrors, formState: { errors } } = useForm();

  useEffect(() => { if (step !== "otp") return; const timer = setInterval(() => { setExpires((x) => Math.max(0, x - 1)); setResend((x) => Math.max(0, x - 1)); }, 1000); return () => clearInterval(timer); }, [step]);
  const isDuplicateEmail = error => error.response?.status === 409 && error.response?.data?.code === "DUPLICATE_EMAIL";
  const showDuplicateEmail = email => { setDuplicateEmail(email || identity?.email || "this email"); setStep("email"); setError("email", { type:"server", message:"An account with this email already exists." }, { shouldFocus:true }); };
  const begin = async (values) => { setBusy(true); clearErrors("email"); const email=values.email.trim().toLowerCase(); try { const payload = { email, ...(isRegister && { name: values.name.trim() }) }; await api.post(isRegister ? "/auth/register" : "/auth/send-otp", payload); setIdentity(payload); setOtp(Array(6).fill("")); setExpires(600); setResend(60); setStep("otp"); toast("Verification code sent to your email."); } catch (error) { if (isRegister && isDuplicateEmail(error)) showDuplicateEmail(email); else toast(apiMessage(error),"error"); } finally { setBusy(false); } };
  const resendOtp = async () => { if (resend || busy) return; setBusy(true); try { await api.post(isRegister ? "/auth/register" : "/auth/send-otp", identity); setOtp(Array(6).fill("")); setExpires(600); setResend(60); toast("A new verification code was sent."); } catch (error) { toast(apiMessage(error), "error"); } finally { setBusy(false); } };
  const verifyOtp = async (event) => { event.preventDefault(); const code = otp.join(""); if (code.length !== 6) return toast("Enter the complete 6-digit code.", "error"); setBusy(true); try { if (isRegister) { const { data } = await api.post("/auth/verify-otp", { ...identity, otp: code }); setRegistrationToken(data.registrationToken); setStep("role"); } else { const { data } = await api.post("/auth/login", { email: identity.email, otp: code }); setUser(data.user); toast("Welcome back to MB Store."); const returnTo=data.user.role==="Customer"&&location.state?.returnTo?location.state.returnTo:roleDestination(data.user.role); navigate(returnTo, { replace: true, state: location.state?.quoteProductId ? { quoteProductId: location.state.quoteProductId } : undefined }); } } catch (error) { if (isRegister && isDuplicateEmail(error)) showDuplicateEmail(identity?.email); else toast(apiMessage(error), "error"); } finally { setBusy(false); } };
  const changeOtp = (index, value) => { const digit = value.replace(/\D/g, "").slice(-1); setOtp((current) => current.map((item, i) => i === index ? digit : item)); if (digit && index < 5) otpRefs.current[index + 1]?.focus(); };
  const pasteOtp = (event) => { const digits = event.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6).split(""); if (!digits.length) return; event.preventDefault(); setOtp(Array.from({ length: 6 }, (_, i) => digits[i] || "")); otpRefs.current[Math.min(digits.length, 6) - 1]?.focus(); };
  const customer = async () => { setBusy(true); try { const { data } = await api.post("/auth/register/customer", { registrationToken }); setUser(data.user); toast("Your customer account is ready."); navigate("/catalogue", { replace: true }); } catch (error) { if (isDuplicateEmail(error)) showDuplicateEmail(identity?.email); else toast(apiMessage(error), "error"); } finally { setBusy(false); } };
  const submitSeller = async ({ businessName, gstNumber, contactPerson }) => { setBusy(true); try { await api.post("/auth/register/seller", { registrationToken, businessName, gstNumber: gstNumber.toUpperCase(), contactPerson }); setSuccess(true); } catch (error) { if (isDuplicateEmail(error)) showDuplicateEmail(identity?.email); else toast(apiMessage(error), "error"); } finally { setBusy(false); } };

  if (success) return <AuthShell><div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-teal-50 text-3xl text-teal-700"><FiBriefcase/></span><h1 className="mt-6 text-3xl font-black text-slate-900">Seller Registration Submitted</h1><p className="mx-auto mt-3 max-w-md leading-7 text-slate-600">Your account is under verification. Our MB Store team will review your GST details, and you’ll receive an email once approved.</p><Link to="/" className="mt-8 inline-flex rounded-xl bg-teal-700 px-6 py-3 font-bold text-white">Go Home</Link></div></AuthShell>;
  return <AuthShell><div className="mx-auto max-w-md"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-700">MB Store secure access</p><h1 className="mt-2 text-3xl font-black text-slate-900">{isRegister ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-slate-500">{step === "email" ? "Use your email to receive a one-time verification code." : step === "otp" ? `Enter the code sent to ${identity?.email}.` : "Complete your registration."}</p>
    {step === "email" && <form onSubmit={handleSubmit(begin)} className="mt-8 space-y-4">{isRegister && <Field icon={FiUser} label="Full name" autoComplete="name" error={errors.name?.message} {...register("name", { required: "Full name is required.", minLength: { value: 2, message: "Enter at least 2 characters." } })}/>}<Field icon={FiMail} label="Email address" type="email" autoComplete="email" placeholder="you@company.com" error={errors.email?.message} {...register("email", { required: "Email is required.", pattern: { value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, message: "Enter a valid email address." } })}/><Submit busy={busy}>Continue</Submit></form>}
    {step === "otp" && <form onSubmit={verifyOtp} className="mt-8"><div className="flex justify-between gap-2" onPaste={pasteOtp}>{otp.map((digit, index) => <input key={index} ref={(node) => { otpRefs.current[index] = node; }} value={digit} onChange={(event) => changeOtp(index, event.target.value)} onKeyDown={(event) => { if (event.key === "Backspace" && !digit && index) otpRefs.current[index - 1]?.focus(); }} inputMode="numeric" autoComplete={index === 0 ? "one-time-code" : "off"} aria-label={`OTP digit ${index + 1}`} className="h-14 w-12 rounded-xl border border-slate-200 text-center text-xl font-black outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100" />)}</div><p className="mt-4 text-center text-sm text-slate-500">Code expires in <strong>{formatTime(expires)}</strong></p><div className="mt-5"><Submit busy={busy || expires === 0}>Verify code</Submit></div><div className="mt-4 flex items-center justify-between text-sm"><button type="button" onClick={() => setStep("email")} className="flex items-center gap-2 font-bold text-slate-500"><FiArrowLeft/>Change email</button><button type="button" disabled={resend > 0 || busy} onClick={resendOtp} className="font-bold text-teal-700 disabled:text-slate-400">{resend ? `Resend in ${resend}s` : "Resend OTP"}</button></div></form>}
    <p className="mt-8 text-center text-sm text-slate-500">{isRegister ? "Already registered?" : "New to MB Store?"} <Link className="font-bold text-teal-700" to={isRegister ? "/login" : "/register"}>{isRegister ? "Log in" : "Register"}</Link></p></div>
    {duplicateEmail && <Modal title="Account Already Exists"><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-bold text-slate-900">{duplicateEmail}</p><p className="mt-1 text-sm leading-6 text-slate-600">This email is already registered with MB Store as an Admin, Seller, or Customer. One email cannot be registered under another account type.</p></div><div className="mt-6 flex gap-3"><button type="button" onClick={()=>setDuplicateEmail("")} className="flex-1 rounded-xl border border-slate-200 px-5 py-3 font-bold text-slate-700">Use another email</button><button type="button" onClick={()=>navigate("/login",{replace:true})} className="flex-1 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Go to Login</button></div></Modal>}
    {step === "role" && <Modal title="How will you use MB Store?"><p className="mt-2 text-slate-500">Choose one option to continue. Roles cannot be changed during login.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><RoleCard icon={FiShoppingBag} title="Customer" copy="Buy products from verified sellers." action="Continue as Customer" onClick={customer} disabled={busy}/><RoleCard icon={FiBriefcase} title="Seller" copy="Sell products on MB Store." action="Continue as Seller" onClick={() => setStep("seller")} disabled={busy}/></div></Modal>}
    {step === "seller" && <Modal title="Seller Registration"><form onSubmit={handleSubmit(submitSeller)} className="mt-6 space-y-4"><Field label="Business name" error={errors.businessName?.message} {...register("businessName", { required: "Business name is required." })}/><Field label="GST number" maxLength="15" className="uppercase" error={errors.gstNumber?.message} {...register("gstNumber", { required: "GST number is required.", pattern: { value: /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/i, message: "Enter a valid 15-character GST number." } })}/><Field label="Contact person" error={errors.contactPerson?.message} {...register("contactPerson", { required: "Contact person is required." })}/><div className="flex gap-3"><button type="button" onClick={() => setStep("role")} className="rounded-xl border border-slate-200 px-5 py-3 font-bold text-slate-700">Back</button><Submit busy={busy}>Verify & submit</Submit></div></form></Modal>}
  </AuthShell>;
}
const roleDestination = (role) => role === "Admin" ? "/admin/dashboard" : role === "Seller" ? "/seller/dashboard" : role === "Support" ? "/support/dashboard" : "/catalogue";
const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
function AuthShell({ children }) { return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-teal-50 via-white to-slate-50 p-4"><section className="w-full max-w-2xl rounded-[2rem] border border-white bg-white/90 p-6 shadow-2xl shadow-teal-950/10 backdrop-blur sm:p-10">{children}</section></main>; }
function Field({ label, error, icon: Icon, className = "", ...props }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><span className="relative block">{Icon && <Icon className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/>}<input className={`w-full rounded-xl border bg-white px-4 py-3.5 outline-none transition focus:border-teal-600 focus:ring-4 focus:ring-teal-100 ${Icon ? "pl-11" : ""} ${error ? "border-red-400" : "border-slate-200"} ${className}`} {...props}/></span>{error && <span className="mt-1.5 block text-sm font-semibold text-red-600">{error}</span>}</label>; }
function Submit({ busy, children, ...props }) { return <button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3.5 font-bold text-white transition hover:bg-teal-800 disabled:cursor-not-allowed disabled:opacity-60" {...props}>{busy && <FiLoader className="animate-spin"/>}{children}</button>; }
function RoleCard({ icon: Icon, title, copy, action, ...props }) { return <button className="group rounded-2xl border border-slate-200 p-5 text-left transition hover:-translate-y-1 hover:border-teal-400 hover:shadow-lg" {...props}><span className="grid h-12 w-12 place-items-center rounded-xl bg-teal-50 text-xl text-teal-700"><Icon/></span><strong className="mt-5 block text-lg text-slate-900">{title}</strong><span className="mt-1 block min-h-12 text-sm leading-6 text-slate-500">{copy}</span><span className="mt-4 block text-sm font-bold text-teal-700">{action} →</span></button>; }
