import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { FiBriefcase, FiEye, FiEyeOff, FiLoader, FiMail, FiShoppingBag, FiUser, FiX } from "react-icons/fi";
import { Link, useLocation, useNavigate } from "react-router-dom";
import api, { apiMessage } from "../../lib/api";
import { useAuth } from "../../context/AuthContext";
import { useToast } from "../../context/ToastContext";

export default function AuthPage({ mode }) {
  const isRegister=mode==="register"; const navigate=useNavigate(); const location=useLocation(); const {setUser,authNotice,clearAuthNotice}=useAuth(); const {toast}=useToast();
  const [busy,setBusy]=useState(false); const [showPassword,setShowPassword]=useState(false); const [registrationData,setRegistrationData]=useState(null); const [popup,setPopup]=useState(null); const [sellerSubmitted,setSellerSubmitted]=useState(false); const [loginNotice,setLoginNotice]=useState("");
  const accountForm=useForm(); const vendorForm=useForm(); const password=accountForm.watch("password");

  useEffect(()=>{setPopup(null);setRegistrationData(null);setSellerSubmitted(false);setLoginNotice("");setBusy(false);accountForm.reset();vendorForm.reset();},[mode]);
  useEffect(()=>{if(!isRegister&&authNotice){toast(authNotice,"error");clearAuthNotice();}},[isRegister,authNotice,clearAuthNotice,toast]);

  const submitAccount=async values=>{
    if(isRegister){setRegistrationData({name:values.name.trim(),email:values.email.trim().toLowerCase(),password:values.password,confirmPassword:values.confirmPassword});setPopup("role");return;}
    setBusy(true);try{const {data}=await api.post("/auth/login",{email:values.email.trim().toLowerCase(),password:values.password});setUser(data.user);toast("Welcome back to MB Store.");const destination=data.user.role==="Customer"&&location.state?.returnTo?location.state.returnTo:roleDestination(data.user.role);navigate(destination,{replace:true});}catch(error){if(error.response?.data?.code==="SELLER_PENDING")setLoginNotice("You are not verified by MB Store yet. Please wait until your seller account is approved.");else toast(apiMessage(error),"error")}finally{setBusy(false)}
  };
  const createCustomer=async()=>{setBusy(true);try{const {data}=await api.post("/auth/register",{...registrationData,role:"customer"});setUser(data.user);toast("Your customer account is ready.");navigate("/customer/home",{replace:true})}catch(error){toast(apiMessage(error),"error")}finally{setBusy(false)}};
  const createVendor=async values=>{setBusy(true);try{await api.post("/auth/register",{...registrationData,role:"seller",businessName:values.businessName.trim(),gstNumber:values.gstNumber.trim().toUpperCase(),contactPerson:registrationData.name});setPopup(null);setSellerSubmitted(true)}catch(error){toast(apiMessage(error),"error")}finally{setBusy(false)}};

  if(sellerSubmitted)return <Shell><div className="text-center"><FiBriefcase className="mx-auto text-5xl text-teal-700"/><h1 className="mt-5 text-3xl font-black">Vendor Registration Submitted</h1><p className="mt-3 leading-7 text-slate-600">Your vendor verification request is being processed by the MB Store team. After the admin verifies your company and GST details, log in to open your vendor dashboard.</p><Link to="/login" className="mt-7 inline-flex rounded-xl bg-teal-700 px-6 py-3 font-bold text-white">Go to login</Link></div></Shell>;

  return <Shell><div className="mx-auto max-w-md"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-700">MB Store secure access</p><h1 className="mt-2 text-3xl font-black text-slate-900">{isRegister?"Create Your MB Store Account":"Welcome Back"}</h1><p className="mt-2 text-slate-500">{isRegister?"Enter your account details. You will choose Customer or Vendor next.":"Enter your email and password. Your role is detected automatically."}</p>
    <form onSubmit={accountForm.handleSubmit(submitAccount)} className="mt-8 space-y-4">{isRegister&&<Field icon={FiUser} label="Full name" placeholder="Enter your full name" autoComplete="name" error={accountForm.formState.errors.name?.message} {...accountForm.register("name",{required:"Full name is required.",minLength:{value:2,message:"Enter at least 2 characters."}})}/>}<Field icon={FiMail} label="Email" type="email" placeholder="you@example.com" autoComplete="email" error={accountForm.formState.errors.email?.message} {...accountForm.register("email",{required:"Email is required.",pattern:{value:/^[^\s@]+@[^\s@]+\.[^\s@]+$/,message:"Enter a valid email address."}})}/><PasswordField label="Password" placeholder={isRegister?"Create a password (minimum 8 characters)":"Enter your password"} autoComplete={isRegister?"new-password":"current-password"} visible={showPassword} toggle={()=>setShowPassword(value=>!value)} error={accountForm.formState.errors.password?.message} {...accountForm.register("password",{required:"Password is required.",minLength:{value:8,message:"Password must contain at least 8 characters."}})}/>{isRegister&&<Field label="Confirm Password" placeholder="Re-enter your password" type={showPassword?"text":"password"} autoComplete="new-password" error={accountForm.formState.errors.confirmPassword?.message} {...accountForm.register("confirmPassword",{required:"Please confirm your password.",validate:value=>value===password||"Passwords do not match."})}/>}<Submit busy={busy}>{isRegister?"Create Account":"Login"}</Submit></form>
    {!isRegister&&<p className="mt-4 text-center text-sm"><Link className="font-bold text-teal-700" to="/forgot-password">Forgot Password?</Link></p>}<p className="mt-6 text-center text-sm text-slate-500">{isRegister?"Already registered?":"Don't have an account?"} <Link className="font-bold text-teal-700" to={isRegister?"/login":"/register"}>{isRegister?"Log in":"Create Account"}</Link></p></div>

    {popup==="role"&&<Modal title="Choose your account type" close={()=>setPopup(null)}><p className="mt-2 text-slate-500">How would you like to use MB Store?</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><RoleCard icon={FiShoppingBag} title="Customer" text="Browse products and request quotations." onClick={createCustomer} disabled={busy}/><RoleCard icon={FiBriefcase} title="Vendor" text="List products after company verification." onClick={()=>setPopup("vendor")} disabled={busy}/></div></Modal>}
    {popup==="Seller"&&<Modal title="Seller company details" close={()=>setPopup("role")}><p className="mt-2 text-slate-500">Your dashboard will become available after admin verification.</p><form onSubmit={vendorForm.handleSubmit(createVendor)} className="mt-6 space-y-4"><Field label="Company name" placeholder="Enter your registered company name" error={vendorForm.formState.errors.businessName?.message} {...vendorForm.register("businessName",{required:"Company name is required.",minLength:{value:2,message:"Enter at least 2 characters."}})}/><Field label="GST number" placeholder="22AAAAA0000A1Z5" maxLength="15" className="uppercase" error={vendorForm.formState.errors.gstNumber?.message} {...vendorForm.register("gstNumber",{required:"GST number is required.",pattern:{value:/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/i,message:"Enter a valid 15-character GST number."}})}/><div className="flex gap-3"><button type="button" onClick={()=>setPopup("role")} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Back</button><Submit busy={busy}>Submit for verification</Submit></div></form></Modal>}
    {loginNotice&&<Modal title="Seller verification pending" close={()=>setLoginNotice("")}><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><p className="leading-7">{loginNotice}</p></div><button type="button" onClick={()=>setLoginNotice("")} className="mt-6 w-full rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Okay</button></Modal>}
  </Shell>;
}

const roleDestination=role=>role==="Admin"?"/admin/dashboard":role==="Seller"?"/seller/dashboard":role==="Support"?"/support/dashboard":"/customer/home";
function Shell({children}){return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-teal-50 via-white to-slate-50 p-4"><section className="w-full max-w-2xl rounded-[2rem] border border-white bg-white/90 p-6 shadow-2xl shadow-teal-950/10 sm:p-10">{children}</section></main>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-black text-slate-900">{title}</h2><button type="button" onClick={close} aria-label="Close" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><FiX/></button></div>{children}</section></div>}
function Field({label,error,icon:Icon,className="",...props}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><span className="relative block">{Icon&&<Icon className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/>}<input className={`w-full rounded-xl border px-4 py-3.5 outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100 ${Icon?"pl-11":""} ${error?"border-red-400":"border-slate-200"} ${className}`} {...props}/></span>{error&&<span className="mt-1 block text-sm font-semibold text-red-600">{error}</span>}</label>}
function PasswordField({visible,toggle,...props}){return <div className="relative"><Field {...props} type={visible?"text":"password"}/><button type="button" aria-label={visible?"Hide password":"Show password"} onClick={toggle} className="absolute right-4 top-11 text-slate-500">{visible?<FiEyeOff/>:<FiEye/>}</button></div>}
function Submit({busy,children}){return <button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3.5 font-bold text-white disabled:opacity-60">{busy&&<FiLoader className="animate-spin"/>}{children}</button>}
function RoleCard({icon:Icon,title,text,...props}){return <button type="button" className="rounded-2xl border border-slate-200 p-5 text-left transition hover:-translate-y-1 hover:border-teal-500 hover:shadow-lg disabled:opacity-60" {...props}><span className="grid h-12 w-12 place-items-center rounded-xl bg-teal-50 text-xl text-teal-700"><Icon/></span><strong className="mt-4 block text-lg">{title}</strong><span className="mt-1 block text-sm leading-6 text-slate-500">{text}</span></button>}
