import {useEffect,useState} from 'react';
import api,{apiMessage} from '../../lib/api';
import {FiArrowRight,FiFileText,FiPlus,FiX} from 'react-icons/fi';
import {PriorityBadge,StatusBadge} from '../../components/support/Badges';
import {useAuth} from '../../context/AuthContext';
import {getCustomerQuotations} from '../../services/quotationService';

const categories=['Login / Account','Profile','Product','Catalogue','Quotation','Enquiry','Chat','Seller Issue','Customer Issue','Technical Issue','Notification','Other'];
const quotationQuestions=[
  ['Seller has not responded','The seller has not responded to my quotation request.'],
  ['Problem with quoted price','I need help regarding the price provided in this quotation.'],
  ['Delivery time issue','I need help regarding the delivery timeline for this quotation.'],
  ['Incorrect product information','The product information related to this quotation appears incorrect.'],
  ['Unable to accept or decline','I am unable to accept or decline this quotation.'],
  ['Other quotation issue','I have another issue related to this quotation.']
];

export default function MySupportTickets(){
  const {user}=useAuth(),customer=user?.role==='Customer';
  const [rows,setRows]=useState([]),[quotations,setQuotations]=useState([]),[selected,setSelected]=useState(null),[create,setCreate]=useState(null),[error,setError]=useState('');
  const load=()=>api.get('/support-tickets').then(({data})=>setRows(data.data));
  useEffect(()=>{load();if(customer)getCustomerQuotations({page:1,limit:6}).then(({data})=>setQuotations(data.data)).catch(()=>{})},[customer]);
  const open=id=>api.get(`/support-tickets/${id}`).then(({data})=>setSelected(data));
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-teal-700">Help & support</p><h1 className="mt-1 text-3xl font-black">My Support Tickets</h1><p className="mt-1 text-sm text-slate-500">Connect with MB Store support about quotations or marketplace issues.</p></div><button onClick={()=>setCreate({})} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/>General Issue</button></div>
    {customer&&<RecentQuotations rows={quotations} ask={quotation=>setCreate({quotation})}/>} {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-600">{error}</p>}
    <section className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black">Your support requests</h2></div><div className="overflow-x-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="bg-slate-50"><tr>{['Ticket','Subject','Category','Priority','Status','Created'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id} onClick={()=>open(r.id)} className="cursor-pointer hover:bg-slate-50"><td className="px-4 py-4 font-mono">{r.ticketNumber}</td><td className="px-4 font-bold">{r.subject}</td><td className="px-4">{r.category}</td><td className="px-4"><PriorityBadge value={r.priority}/></td><td className="px-4"><StatusBadge value={r.status}/></td><td className="px-4">{new Date(r.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-slate-400">No support tickets yet.</p>}</div></section>
    {create&&<Create initial={create} customer={customer} quotations={quotations} close={()=>setCreate(null)} done={()=>{setCreate(null);load()}} fail={e=>setError(apiMessage(e))}/>} {selected&&<Details data={selected} close={()=>setSelected(null)} reload={()=>open(selected.ticket.id)}/>}</>;
}

function RecentQuotations({rows,ask}){return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-xl font-black">Need help with a recent quotation?</h2><p className="mt-1 text-sm text-slate-500">Choose a quotation below and tell support what went wrong.</p></div>{rows.length?<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(q=><article key={q.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><FiFileText/></span><div className="min-w-0"><b className="block font-mono text-sm">{q.quotation_number}</b><h3 className="mt-1 truncate font-bold">{q.product_name_snapshot}</h3><p className="mt-1 truncate text-xs text-slate-500">{q.seller_company_snapshot} · {q.quantity} units</p></div></div><div className="mt-4 flex items-center justify-between"><StatusBadge value={q.status}/><button onClick={()=>ask(q)} className="flex items-center gap-1 text-sm font-bold text-teal-700">Ask Support <FiArrowRight/></button></div></article>)}</div>:<p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">You have no recent quotations. Use General Issue if you still need help.</p>}</section>}

function Create({initial,customer,quotations,close,done,fail}){
  const selectedQuotation=initial.quotation;
  const [question,setQuestion]=useState(selectedQuotation?quotationQuestions[0][0]:'');
  const [f,setF]=useState({subject:selectedQuotation?quotationQuestions[0][0]:'',description:selectedQuotation?quotationQuestions[0][1]:'',category:selectedQuotation?'Quotation':'Other',priority:'Medium',relatedQuotationId:selectedQuotation?.id||''});
  const choose=value=>{setQuestion(value);const item=quotationQuestions.find(x=>x[0]===value);setF({...f,subject:value,description:item?.[1]||'',category:'Quotation'})};
  const quotation=quotations.find(q=>String(q.id)===String(f.relatedQuotationId));
  const submit=async e=>{e.preventDefault();try{await api.post('/support-tickets',f);done()}catch(x){fail(x)}};
  return <Modal close={close} title={customer?'Connect with Support':'Report an issue'}><form onSubmit={submit} className="space-y-4">
    {customer&&<><label className="block text-sm font-bold">Related quotation<select value={f.relatedQuotationId} onChange={e=>{const value=e.target.value,first=quotationQuestions[0];setQuestion(value?first[0]:'');setF({...f,relatedQuotationId:value,category:value?'Quotation':'Other',subject:value?first[0]:'',description:value?first[1]:''})}} className="input"><option value="">General issue — no quotation</option>{quotations.map(q=><option key={q.id} value={q.id}>{q.quotation_number} — {q.product_name_snapshot} — {q.seller_company_snapshot}</option>)}</select></label>{quotation&&<div className="rounded-xl bg-slate-50 p-4 text-sm"><b>{quotation.product_name_snapshot}</b><p className="mt-1 text-slate-500">{quotation.seller_company_snapshot} · Status: {quotation.status}</p></div>}{f.relatedQuotationId&&<label className="block text-sm font-bold">What do you need help with?<select value={question} onChange={e=>choose(e.target.value)} className="input">{quotationQuestions.map(([label])=><option key={label}>{label}</option>)}</select></label>}</>}
    <label className="block text-sm font-bold">Question / Subject<input required value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} className="input" placeholder="How can support help?"/></label><label className="block text-sm font-bold">Explain the problem<textarea required rows="5" value={f.description} onChange={e=>setF({...f,description:e.target.value})} className="input" placeholder="Add details that will help us resolve the issue..."/></label>{!f.relatedQuotationId&&<select value={f.category} onChange={e=>setF({...f,category:e.target.value})} className="input">{categories.map(x=><option key={x}>{x}</option>)}</select>}<label className="block text-sm font-bold">Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})} className="input">{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></label><button className="w-full rounded-xl bg-teal-700 py-3 font-bold text-white">Send to Support</button></form></Modal>;
}

function Details({data,close,reload}){const [message,setMessage]=useState('');const readOnly=['Resolved','Closed'].includes(data.ticket.status);return <Modal close={close} title={data.ticket.ticketNumber}><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-black">{data.ticket.subject}</h3><StatusBadge value={data.ticket.status}/></div><p className="mt-2 text-sm text-slate-600">{data.ticket.description}</p>{data.ticket.quotationNumber&&<p className="mt-3 rounded-xl bg-teal-50 p-3 text-sm font-bold text-teal-800">Related quotation: {data.ticket.quotationNumber}</p>}<div className="mt-5 max-h-72 space-y-2 overflow-auto">{data.messages.map(m=><div key={m.id} className="rounded-xl border p-3"><b className="text-sm">{m.senderName}</b><p className="text-sm">{m.message}</p></div>)}{!data.messages.length&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-400">No conversation messages yet.</p>}</div>{readOnly?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-800">This ticket has been {data.ticket.status.toLowerCase()}.</p><p className="mt-1 text-sm text-emerald-700">The conversation is now read-only. You can continue to view the complete chat history.</p></div>:<form onSubmit={async e=>{e.preventDefault();await api.post(`/support-tickets/${data.ticket.id}/messages`,{message});setMessage('');reload()}} className="mt-4 flex gap-2"><input required value={message} onChange={e=>setMessage(e.target.value)} className="input mt-0" placeholder="Reply to support..."/><button className="rounded-xl bg-teal-700 px-5 font-bold text-white">Reply</button></form>}</Modal>}
const Modal=({close,title,children})=><div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}><FiX/></button></div>{children}</section></div>;
