import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip,AreaChart,Area,XAxis,YAxis,CartesianGrid} from 'recharts';
import {FiAlertTriangle,FiCheckCircle,FiClock,FiInbox} from 'react-icons/fi';
import {supportApi} from '../../services/supportService';
import {PriorityBadge,StatusBadge} from '../../components/support/Badges';
const colors=['#0f766e','#2563eb','#f59e0b','#ef4444','#8b5cf6','#64748b'];
const duration=m=>!m?'—':m<60?`${Math.round(m)}m`:`${Math.floor(m/60)}h ${Math.round(m%60)}m`;
export default function SupportDashboard(){const [data,setData]=useState(null);useEffect(()=>{supportApi.dashboard().then(({data})=>setData(data))},[]);const m=data?.metrics||{};const cards=[['Open Tickets',m.openTickets,FiInbox],['New Today',m.newToday,FiInbox],['Pending Response',m.pendingResponse,FiClock],['High Priority',m.highPriority,FiAlertTriangle],['Resolved Today',m.resolvedToday,FiCheckCircle],['Overdue',m.overdue,FiAlertTriangle],['Avg First Response',duration(m.avgFirstResponseMinutes),FiClock],['Avg Resolution',duration(m.avgResolutionMinutes),FiClock]];return <div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-widest text-teal-700">Support operations</p><h1 className="mt-1 text-3xl font-black">Dashboard</h1><p className="mt-1 text-slate-500">Live workload, SLA health and team activity.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([name,value,Icon])=><article key={name} className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon/></span><strong className="mt-4 block text-3xl">{data?value??0:'—'}</strong><p className="mt-1 text-sm text-slate-500">{name}</p></article>)}</div><div className="grid gap-5 xl:grid-cols-2"><Chart title="Tickets by Status"><ResponsiveContainer><PieChart><Pie data={data?.byStatus||[]} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{(data?.byStatus||[]).map((x,i)=><Cell key={x.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Chart><Chart title="Created vs Resolved"><ResponsiveContainer><AreaChart data={data?.timeline||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Area dataKey="created" stroke="#0f766e" fill="#ccfbf1"/><Area dataKey="resolved" stroke="#2563eb" fill="#dbeafe"/></AreaChart></ResponsiveContainer></Chart></div><div className="grid gap-5 xl:grid-cols-2"><TicketList title="Needs Attention" rows={data?.needsAttention||[]}/><TicketList title="Recent Tickets" rows={data?.recentTickets||[]}/></div></div>}
const Chart=({title,children})=><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">{title}</h2><div className="mt-4 h-72">{children}</div></section>;
const TicketList=({title,rows})=><section className="rounded-2xl border bg-white shadow-sm"><div className="flex justify-between border-b p-5"><h2 className="font-black">{title}</h2><Link to="/support/tickets" className="text-sm font-bold text-teal-700">View all</Link></div><div className="divide-y">{rows.map(r=><Link to="/support/tickets" key={r.id} className="flex items-center gap-3 p-4 hover:bg-slate-50"><div className="min-w-0 flex-1"><b className="block truncate text-sm">{r.ticket_number} · {r.subject}</b><span className="text-xs text-slate-500">{r.customerName||r.sellerName||'Support'}</span></div><PriorityBadge value={r.priority}/><StatusBadge value={r.status}/></Link>)}{!rows.length&&<p className="p-8 text-center text-sm text-slate-400">No tickets.</p>}</div></section>;
