import {useCallback,useEffect,useState} from 'react';
import {FiEye,FiPlus,FiSearch,FiX} from 'react-icons/fi';
import {useLocation} from 'react-router-dom';
import {supportApi} from '../../services/supportService';
import {apiMessage} from '../../lib/api';
import {PriorityBadge,StatusBadge} from '../../components/support/Badges';

const categories=['Login / Account','Profile','Product','Catalogue','Quotation','Enquiry','Chat','Seller Issue','Customer Issue','Technical Issue','Notification','Other'];
const scopeFrom=path=>path.endsWith('/my')?'my':path.endsWith('/unassigned')?'unassigned':path.endsWith('/high-priority')?'high':path.endsWith('/resolved')?'resolved':'';
export default function SupportTickets(){const location=useLocation(),scope=scopeFrom(location.pathname);const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[create,setCreate]=useState(false),[filters,setFilters]=useState({search:'',status:'',priority:'',category:'',page:1}),[pagination,setPagination]=useState({});
 const load=useCallback(()=>{setLoading(true);supportApi.tickets({...filters,scope:scope||undefined}).then(({data})=>{setRows(data.data);setPagination(data.pagination);setError('')}).catch(e=>setError(apiMessage(e))).finally(()=>setLoading(false))},[filters,scope]);useEffect(load,[load]);
 const open=async id=>{const {data}=await supportApi.ticket(id);setSelected(data)};
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-teal-700">Ticket workspace</p><h1 className="mt-1 text-3xl font-black">{scope?`${scope.replace('-',' ')} tickets`:'All Tickets'}</h1></div><button onClick={()=>setCreate(true)} className="flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><FiPlus/>Create Ticket</button></div>
 <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-4"><label className="flex items-center gap-2 rounded-xl border px-3"><FiSearch/><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value,page:1})} placeholder="Search tickets..." className="w-full py-3 outline-none"/></label><Select value={filters.status} onChange={v=>setFilters({...filters,status:v,page:1})} label="All statuses" options={['New','Assigned','In Progress','Waiting for Customer','Waiting for Seller','Resolved','Closed']}/><Select value={filters.priority} onChange={v=>setFilters({...filters,priority:v,page:1})} label="All priorities" options={['Low','Medium','High','Critical']}/><Select value={filters.category} onChange={v=>setFilters({...filters,category:v,page:1})} label="All categories" options={categories}/></div>
 {loading?<div className="h-72 animate-pulse bg-slate-100"/>:error?<p className="p-10 text-center text-red-600">{error}</p>:<div className="overflow-x-auto"><table className="w-full min-w-250 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{['Ticket ID','User','Type','Subject','Category','Priority','Assigned Support','Status','Created','Actions'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-4 py-4 font-mono text-xs">{r.ticket_number}</td><td className="px-4 font-bold">{r.customerName||r.sellerName||'Support'}</td><td className="px-4">{r.created_by_type}</td><td className="max-w-56 truncate px-4">{r.subject}</td><td className="px-4">{r.category}</td><td className="px-4"><PriorityBadge value={r.priority}/></td><td className="px-4">{r.supportName||'Unassigned'}</td><td className="px-4"><StatusBadge value={r.status}/></td><td className="px-4 text-slate-500">{new Date(r.created_at).toLocaleDateString()}</td><td className="px-4"><button onClick={()=>open(r.id)} className="rounded-lg border p-2"><FiEye/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-slate-400">No tickets found.</p>}</div>}<div className="flex justify-between border-t p-4 text-sm"><span>{pagination.total||0} tickets</span><div className="flex gap-2"><button disabled={filters.page<=1} onClick={()=>setFilters({...filters,page:filters.page-1})} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={filters.page>=pagination.totalPages} onClick={()=>setFilters({...filters,page:filters.page+1})} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div></section>
 {selected&&<TicketDetails data={selected} close={()=>setSelected(null)} reload={async()=>{await load();await open(selected.ticket.id)}}/>}{create&&<CreateTicket close={()=>setCreate(false)} done={()=>{setCreate(false);load()}}/>}</>}
const Select=({value,onChange,label,options})=><select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border bg-white px-3"><option value="">{label}</option>{options.map(x=><option key={x}>{x}</option>)}</select>;
function CreateTicket({close,done}){const [form,setForm]=useState({subject:'',description:'',category:'Other',priority:'Medium',customerId:'',sellerId:'',relatedQuotationId:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);try{await supportApi.createTicket(form);done()}catch(x){setError(apiMessage(x))}finally{setBusy(false)}};return <Modal close={close} title="Create support ticket"><form onSubmit={submit} className="space-y-4"><Input label="Subject" value={form.subject} set={v=>setForm({...form,subject:v})}/><label className="block text-sm font-bold">Description<textarea required rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input"/></label><div className="grid grid-cols-2 gap-3"><Select value={form.category} onChange={v=>setForm({...form,category:v})} options={categories}/><Select value={form.priority} onChange={v=>setForm({...form,priority:v})} options={['Low','Medium','High','Critical']}/></div><div className="grid grid-cols-3 gap-3"><Input label="Customer ID" type="number" value={form.customerId} set={v=>setForm({...form,customerId:v})}/><Input label="Seller ID" type="number" value={form.sellerId} set={v=>setForm({...form,sellerId:v})}/><Input label="Quotation ID" type="number" value={form.relatedQuotationId} set={v=>setForm({...form,relatedQuotationId:v})}/></div>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-teal-700 py-3 font-bold text-white">{busy?'Creating...':'Create Ticket'}</button></form></Modal>}
function TicketDetails({data,close,reload}){const {ticket,messages,internalNotes}=data,[text,setText]=useState(''),[note,setNote]=useState('');const act=async fn=>{await fn();await reload()};return <Modal close={close} title={ticket.ticket_number} wide><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div><div className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">{ticket.subject}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{ticket.description}</p></div><h3 className="mt-5 font-black">Conversation</h3><div className="mt-2 max-h-72 space-y-2 overflow-auto">{messages.map(m=><div key={m.id} className="rounded-xl border p-3"><b className="text-sm">{m.senderName} · {m.audience}</b><p className="mt-1 text-sm">{m.message}</p></div>)}</div><form onSubmit={e=>{e.preventDefault();act(()=>supportApi.message(ticket.id,{message:text,audience:'All'}));setText('')}} className="mt-3 flex gap-2"><input required value={text} onChange={e=>setText(e.target.value)} className="input mt-0" placeholder="Reply..."/><button className="rounded-xl bg-teal-700 px-4 font-bold text-white">Send</button></form></div><aside className="space-y-3"><div className="rounded-xl border p-4"><div className="flex justify-between"><PriorityBadge value={ticket.priority}/><StatusBadge value={ticket.status}/></div><p className="mt-4 text-sm">Customer: <b>{ticket.customerName||'—'}</b></p><p className="mt-2 text-sm">Seller: <b>{ticket.sellerCompany||ticket.sellerName||'—'}</b></p><p className="mt-2 text-sm">Product: <b>{ticket.productName||'—'}</b></p><p className="mt-2 text-sm">Quotation: <b>{ticket.quotationNumber||'—'}</b></p></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>act(()=>supportApi.assign(ticket.id))} className="rounded-xl border p-2 font-bold">Assign to me</button><button onClick={()=>act(()=>supportApi.updateTicket(ticket.id,{status:'Resolved'}))} className="rounded-xl bg-emerald-600 p-2 font-bold text-white">Resolve</button><button onClick={()=>text&&act(()=>supportApi.forward(ticket.id,'seller',{message:text}))} className="rounded-xl border p-2 text-sm font-bold">Forward Seller</button><button onClick={()=>text&&act(()=>supportApi.forward(ticket.id,'customer',{message:text}))} className="rounded-xl border p-2 text-sm font-bold">Forward Customer</button></div><h3 className="font-black">Internal notes</h3>{internalNotes.map(n=><p key={n.id} className="rounded-xl bg-amber-50 p-3 text-sm">{n.note}</p>)}<form onSubmit={e=>{e.preventDefault();act(()=>supportApi.note(ticket.id,note));setNote('')}}><textarea required value={note} onChange={e=>setNote(e.target.value)} rows="2" className="input" placeholder="Private note..."/><button className="mt-2 w-full rounded-xl border py-2 font-bold">Add note</button></form></aside></div></Modal>}
const Input=({label,value,set,type='text'})=><label className="block text-sm font-bold">{label}<input required={label==='Subject'} type={type} value={value} onChange={e=>set(e.target.value)} className="input"/></label>;
const Modal=({close,title,children,wide})=><div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4"><section className={`max-h-[92vh] w-full overflow-auto rounded-3xl bg-white p-6 ${wide?'max-w-6xl':'max-w-2xl'}`}><header className="mb-5 flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}><FiX/></button></header>{children}</section></div>;
