import {useEffect} from "react";
import {FiPlus,FiTrash2} from "react-icons/fi";
import {getAdminCategory} from "../../services/categoryService";

const blank=()=>({fieldLabel:"",fieldType:"text",required:true});
export const newCategoryFields=()=>[blank()];
export function validateCategoryDraft(form){const errors={};const name=String(form.name||"").trim();if(name.length<2||name.length>120)errors.name="Category name must be between 2 and 120 characters.";if(!Array.isArray(form.attributes)||form.attributes.length<1||form.attributes.length>5)errors.attributes="Add between 1 and 5 attributes.";const seen=new Set();errors.fields=(form.attributes||[]).map(field=>{const label=String(field.fieldLabel||"").trim(),key=label.toLowerCase().replace(/[^a-z0-9]+/g,"_");if(label.length<2||label.length>120)return "Attribute name must be between 2 and 120 characters.";if(seen.has(key))return "Attribute names must be unique.";seen.add(key);return ""});return errors;}
export default function CategoryFieldsEditor({form,setForm,errors={}}){
  const attributes=form.attributes||[];
  useEffect(()=>{if(!form.id||form.attributes)return;getAdminCategory(form.id).then(({data})=>setForm(current=>({...current,attributes:data.category.fields.map(field=>({fieldLabel:field.fieldLabel,fieldType:field.fieldType,required:field.required}))})))},[form.id,form.attributes,setForm]);
  const update=(index,key,value)=>setForm(current=>({...current,attributes:(current.attributes||newCategoryFields()).map((field,i)=>i===index?{...field,[key]:value}:field)}));
  const remove=index=>setForm(current=>({...current,attributes:current.attributes.filter((_,i)=>i!==index)}));
  if(!form.attributes)return <div className="h-40 animate-pulse rounded-2xl bg-slate-100"/>;
  return <div className="space-y-5"><label className="block text-sm font-bold">Category Name<input autoFocus value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value}))} className={`mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-teal-600 ${errors.name?"border-red-400":""}`} placeholder="Enter category name"/>{errors.name&&<span className="mt-1 block text-xs text-red-600">{errors.name}</span>}</label><div><div className="flex items-center justify-between"><div><p className="text-sm font-black">Seller Attributes</p><p className="text-xs text-slate-500">Add 1 to 5 field names. Sellers enter the values.</p></div><button type="button" disabled={attributes.length>=5} onClick={()=>setForm(current=>({...current,attributes:[...current.attributes,blank()]}))} className="flex items-center gap-1 rounded-lg border border-teal-200 px-3 py-2 text-xs font-bold text-teal-700 disabled:opacity-40"><FiPlus/>Add Attribute</button></div>{errors.attributes&&<p className="mt-2 text-xs text-red-600">{errors.attributes}</p>}<div className="mt-3 space-y-3">{attributes.map((field,index)=><div key={index} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="grid gap-3 sm:grid-cols-[1fr_130px_auto]"><label className="text-xs font-bold text-slate-600">Attribute {index+1}<input value={field.fieldLabel} onChange={event=>update(index,"fieldLabel",event.target.value)} className={`mt-1 w-full rounded-lg border bg-white px-3 py-2.5 outline-none ${errors.fields?.[index]?"border-red-400":"focus:border-teal-600"}`} placeholder="e.g. Technology"/></label><label className="text-xs font-bold text-slate-600">Field Type<select value={field.fieldType} onChange={event=>update(index,"fieldType",event.target.value)} className="mt-1 w-full rounded-lg border bg-white px-3 py-2.5"><option value="text">Text</option><option value="number">Number</option><option value="textarea">Textarea</option><option value="boolean">Yes / No</option></select></label><button type="button" disabled={attributes.length===1} onClick={()=>remove(index)} className="mt-5 grid size-10 place-items-center rounded-lg border border-red-200 text-red-600 disabled:opacity-30"><FiTrash2/></button></div>{errors.fields?.[index]&&<p className="mt-1 text-xs text-red-600">{errors.fields[index]}</p>}<label className="mt-3 flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={field.required} onChange={event=>update(index,"required",event.target.checked)} className="size-4 accent-teal-700"/>Required for sellers</label></div>)}</div></div></div>;
}
