import {useEffect,useMemo,useState} from "react";
import {FiHeart,FiSearch} from "react-icons/fi";
import {Link} from "react-router-dom";
import ProductCard from "../../components/ProductCard";
import ProductSkeleton from "../../components/Loader/ProductSkeleton";
import {useWishlist} from "../../context/WishlistContext";
import CustomerLayout from "../../layout/customer/CustomerLayout";
import {apiMessage} from "../../lib/api";
import {getWishlist} from "../../services/wishlistService";

export default function Wishlist(){
  const wishlist=useWishlist();
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[sort,setSort]=useState("recent");
  const load=async()=>{setLoading(true);setError("");try{const {data}=await getWishlist();setItems(data.items)}catch(requestError){setError(apiMessage(requestError))}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>{const query=search.trim().toLowerCase();const filtered=items.filter(item=>wishlist.isWishlisted(item.product.id)&&(!query||[item.product.productName,item.product.brand,item.product.sellerCompany].some(value=>String(value).toLowerCase().includes(query))));return [...filtered].sort((a,b)=>sort==="oldest"?new Date(a.createdAt)-new Date(b.createdAt):sort==="az"?a.product.productName.localeCompare(b.product.productName):sort==="za"?b.product.productName.localeCompare(a.product.productName):new Date(b.createdAt)-new Date(a.createdAt))},[items,wishlist,search,sort]);
  const cards=visible.map(item=>{const product=item.product,attributes=Object.fromEntries(product.attributes.map(value=>[value.fieldKey,value.fieldValue]));return{id:product.id,name:product.productName,company:product.sellerCompany,brand:product.brand,category:product.categoryName,image:product.imageUrl,availability:product.availability,technology:attributes.technology||attributes.type,power:attributes.power||attributes.capacity}});
  return <CustomerLayout title="Wishlist"><section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-teal-700">Saved products</p><h1 className="text-3xl font-black">My Wishlist</h1><p className="mt-1 text-sm text-slate-500">{visible.length} saved product{visible.length===1?"":"s"}</p></div><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5"><FiSearch/><input value={search} onChange={event=>setSearch(event.target.value)} className="outline-none" placeholder="Search wishlist"/></label><select value={sort} onChange={event=>setSort(event.target.value)} className="rounded-xl border bg-white px-4"><option value="recent">Recently Added</option><option value="oldest">Oldest Added</option><option value="az">Product A-Z</option><option value="za">Product Z-A</option></select></div></div>{loading?<div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{Array.from({length:6},(_,index)=><ProductSkeleton key={index}/>)}</div>:error?<div className="mt-6 rounded-3xl border bg-white p-10 text-center"><p className="font-bold text-red-700">Unable to load your wishlist.</p><button onClick={load} className="mt-4 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Try Again</button></div>:cards.length?<div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{cards.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<div className="mt-6 grid min-h-80 place-items-center rounded-3xl border border-dashed bg-white text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-red-50 text-2xl text-red-500"><FiHeart/></span><h2 className="mt-4 text-xl font-black">Your Wishlist is Empty</h2><p className="mt-2 text-sm text-slate-500">Save products you're interested in by clicking the heart icon.</p><Link to="/catalogue" className="mt-5 inline-flex rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Browse Products</Link></div></div>}</section></CustomerLayout>;
}
