import { FiArrowRight, FiBriefcase, FiCheckCircle } from "react-icons/fi";
import { Link } from "react-router-dom";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import { products } from "../../data/products";

const companyList=Object.values(products.reduce((all,product)=>{if(!all[product.company])all[product.company]={name:product.company,brands:new Set(),categories:new Set(),count:0};const company=all[product.company];company.count+=1;company.brands.add(product.brand);company.categories.add(product.category);return all},{})).map(company=>({...company,brands:[...company.brands],categories:[...company.categories]})).sort((a,b)=>a.name.localeCompare(b.name));

export default function Companies(){return <><Navbar/><main className="min-h-screen bg-slate-50"><section className="section-shell py-10 md:py-14"><div className="mb-7"><h1 className="text-3xl font-black tracking-tight text-slate-900">All Companies</h1><p className="mt-1 text-sm text-slate-500">{companyList.length} companies available</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{companyList.map(company=><article key={company.name} className="group flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-xl"><div className="placeholder-pattern flex aspect-[2/1] items-center justify-center rounded-xl border border-slate-200 text-slate-400"><div className="text-center"><FiBriefcase className="mx-auto mb-2 text-3xl"/><span className="text-xs font-bold">Company Logo</span></div></div><div className="flex-1 pt-5"><div className="flex items-start justify-between gap-3"><h2 className="font-black text-slate-900">{company.name}</h2><FiCheckCircle className="shrink-0 text-sky-600" aria-label="Verified company"/></div><p className="mt-2 text-xs font-semibold text-slate-500">{company.brands.join(", ")}</p><div className="mt-4 flex flex-wrap gap-1.5">{company.categories.slice(0,3).map(category=><span key={category} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{category}</span>)}</div></div><Link to={`/catalogue?company=${encodeURIComponent(company.name)}`} className="mt-5 inline-flex items-center justify-between rounded-xl bg-sky-600 px-4 py-3 text-sm font-extrabold text-white transition group-hover:bg-sky-700">View {company.count} Products<FiArrowRight/></Link></article>)}</div></section></main><Footer/></>}
