import { useCallback, useEffect, useState } from "react";
import { FiArrowRight, FiBriefcase, FiChevronLeft, FiChevronRight, FiSearch } from "react-icons/fi";
import { Link } from "react-router-dom";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";

export default function Companies(){
  const {toast}=useToast(); const [companies,setCompanies]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[meta,setMeta]=useState({totalRecords:0,totalPages:1});
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1)},300);return()=>clearTimeout(timer)},[search]);
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await api.get("/companies",{params:{search:query||undefined,page,limit:24}});setCompanies(data.data);setMeta(data)}catch(error){setCompanies([]);toast(apiMessage(error),"error")}finally{setLoading(false)}},[query,page,toast]); useEffect(()=>{load()},[load]);
  return <><Navbar/><main className="min-h-screen bg-slate-50"><section className="section-shell py-10 md:py-14"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-600">MB Store network</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900 md:text-4xl">All Companies</h1><p className="mt-2 text-sm text-slate-500">{loading?"Loading companies...":`${meta.totalRecords} ${meta.totalRecords===1?"company":"companies"}`}</p></div><label className="flex w-full max-w-md items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm transition focus-within:border-sky-400 focus-within:ring-4 focus-within:ring-sky-100"><FiSearch className="text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} className="w-full text-sm outline-none" placeholder="Search companies..."/></label></div>
  <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{loading?Array.from({length:8},(_,index)=><article key={index} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="aspect-[2/1] animate-pulse rounded-xl bg-slate-200"/><div className="mt-5 h-5 w-2/3 animate-pulse rounded bg-slate-200"/><div className="mt-3 h-4 w-1/3 animate-pulse rounded bg-slate-100"/></article>):companies.map(company=><article key={company.id} className="group flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-xl"><div className="flex aspect-[2/1] items-center justify-center overflow-hidden rounded-xl border border-slate-100 bg-white p-4"><img src={`${api.defaults.baseURL}${company.logoUrl}`} alt={`${company.companyName} logo`} className="max-h-full max-w-full object-contain"/></div><div className="flex-1 pt-5"><h2 className="text-lg font-black text-slate-900">{company.companyName}</h2></div><Link to={`/catalogue?company=${encodeURIComponent(company.companyName)}`} className="mt-5 inline-flex items-center justify-between rounded-xl bg-sky-600 px-4 py-3 text-sm font-extrabold text-white transition group-hover:bg-sky-700">View Products<FiArrowRight/></Link></article>)}</div>
  {!loading&&!companies.length&&<div className="mt-8 grid min-h-80 place-items-center rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-slate-100 text-2xl text-slate-400"><FiBriefcase/></span><h2 className="mt-4 text-xl font-black">{query?"No matching companies":"No companies available"}</h2><p className="mt-2 text-sm text-slate-500">{query?"Try a different company name.":"Companies will appear here when available."}</p></div></div>}
  {meta.totalPages>1&&<div className="mt-8 flex items-center justify-center gap-3"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="grid size-10 place-items-center rounded-xl border border-slate-200 bg-white disabled:opacity-40"><FiChevronLeft/></button><span className="text-sm font-bold text-slate-600">Page {page} of {meta.totalPages}</span><button disabled={page>=meta.totalPages} onClick={()=>setPage(value=>value+1)} className="grid size-10 place-items-center rounded-xl border border-slate-200 bg-white disabled:opacity-40"><FiChevronRight/></button></div>}</section></main><Footer/></>;
}
