import { useCallback, useEffect, useMemo, useState } from "react";
import { FiArrowUpRight, FiBox, FiBriefcase, FiCheck, FiClock, FiEye, FiMoreHorizontal, FiUsers } from "react-icons/fi";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api, { apiMessage } from "../../lib/api";
import { useToast } from "../../context/ToastContext";
import { useAuth } from "../../context/AuthContext";
import { products } from "../../data/products";
import DashboardShell from "./DashboardShell";

const chartData = [
  { month: "Jan", sellers: 120, customers: 380 }, { month: "Feb", sellers: 175, customers: 445 },
  { month: "Mar", sellers: 158, customers: 510 }, { month: "Apr", sellers: 230, customers: 590 },
  { month: "May", sellers: 280, customers: 545 }, { month: "Jun", sellers: 315, customers: 680 },
  { month: "Jul", sellers: 360, customers: 760 }, { month: "Aug", sellers: 410, customers: 850 },
];
const orders = [
  ["Waaree 550W Module", "SolarGrid Solutions", "#QT-1048", "05 Aug 2026", "Pending"],
  ["ABB MCCB 125A", "Mehta Industries", "#QT-1047", "04 Aug 2026", "Approved"],
  ["Growatt 5kW Inverter", "Sunrise Power", "#QT-1046", "03 Aug 2026", "Processing"],
];
const sellerAvatars = ["RS", "AK", "NM"];

function StatCard({ label, value, change, icon: Icon, tone }) {
  return <article className={`rounded-2xl p-5 ${tone}`}><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-3 text-3xl font-black tracking-tight">{value}</p></div><span className="grid size-11 place-items-center rounded-xl bg-white/70 text-xl"><Icon /></span></div><p className="mt-5 flex items-center gap-1 text-xs text-slate-500"><span className="flex items-center font-bold text-emerald-700"><FiArrowUpRight />{change}</span> from last month</p></article>;
}
function SectionTitle({ children, action }) { return <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-black">{children}</h2>{action || <FiMoreHorizontal className="text-slate-400" />}</div>; }

export default function AdminDashboard() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const { data } = await api.get("/admin/seller-requests"); setRequests(data.requests); } catch (error) { toast(apiMessage(error), "error"); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const act = async (id, action) => { try { await api.put(`/admin/${action}/${id}`, action === "reject" ? { reason: "Rejected by administrator" } : {}); setRequests((items) => items.filter((item) => item.id !== id)); toast(`Seller ${action === "approve" ? "approved" : "rejected"}.`); } catch (error) { toast(apiMessage(error), "error"); } };
  const topProducts = useMemo(() => [products[0], products[4], products[18]], []);
  const recentSellers = requests.slice(0, 3);

  return <DashboardShell><div className="mx-auto max-w-[1600px]">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-black sm:text-3xl">Welcome back, {user?.name?.split(" ")[0] || "Admin"}!</h1><p className="mt-1 text-sm text-slate-500">Here’s what’s happening across MB Store today.</p></div><div className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">August 2026</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Total Companies" value="128" change="12.4%" icon={FiBriefcase} tone="bg-[#f9eee1]" /><StatCard label="Total Sellers" value="684" change="8.6%" icon={FiUsers} tone="bg-[#eaf3e4]" /><StatCard label="Total Customers" value="2,840" change="14.8%" icon={FiUsers} tone="bg-[#e7eef9]" /><StatCard label="Total Products" value={products.length} change="6.2%" icon={FiBox} tone="bg-[#e7f3f1]" /><StatCard label="Pending Approvals" value={loading ? "—" : requests.length} change="2 new" icon={FiClock} tone="bg-[#f7e9ec]" /></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.8fr)_minmax(310px,.8fr)]"><section className="rounded-2xl border border-slate-200 bg-white"><SectionTitle action={<select className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold"><option>Last 8 months</option></select>}>Seller & Customer Analytics</SectionTitle><div className="h-80 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="customers" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22c55e" stopOpacity={.25}/><stop offset="95%" stopColor="#22c55e" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eef0f3" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#94a3b8",fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#94a3b8",fontSize:12}}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid #e2e8f0"}}/><Area type="monotone" dataKey="customers" stroke="#22c55e" strokeWidth={3} fill="url(#customers)"/><Area type="monotone" dataKey="sellers" stroke="#0f766e" strokeWidth={3} fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="flex justify-center gap-6 pb-5 text-xs font-semibold text-slate-500"><span><i className="mr-2 inline-block size-2 rounded-full bg-green-500"/>Customers</span><span><i className="mr-2 inline-block size-2 rounded-full bg-teal-700"/>Sellers</span></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white"><SectionTitle>Most Quoted Products</SectionTitle><div className="divide-y divide-slate-100 px-5">{topProducts.map((product, index) => <div key={product.id} className="flex items-center gap-3 py-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-slate-100 text-xl">{["☀", "⚡", "▣"][index]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.name}</p><p className="truncate text-xs text-slate-400">{product.company}</p></div><span className="rounded-lg bg-slate-50 px-2.5 py-1.5 text-xs font-bold">{[148, 102, 87][index]} quotes</span></div>)}</div></section>
    </div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.8fr)_minmax(310px,.8fr)]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><SectionTitle action={<button className="flex items-center gap-1 text-xs font-bold text-teal-700">View all <FiArrowUpRight /></button>}>Recent Orders</SectionTitle><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr>{["Product", "Company", "Quote ID", "Date", "Status", ""].map((x) => <th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{orders.map((row) => <tr key={row[2]}>{row.map((cell, i) => <td key={i} className={`px-5 py-4 ${i === 0 ? "font-bold" : "text-slate-500"}`}>{i === 4 ? <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${cell === "Approved" ? "bg-emerald-50 text-emerald-700" : cell === "Pending" ? "bg-amber-50 text-amber-700" : "bg-blue-50 text-blue-700"}`}>{cell}</span> : cell}</td>)}<td className="px-5"><button className="text-slate-400"><FiEye /></button></td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white"><SectionTitle action={<button className="text-xs font-bold text-teal-700">View all</button>}>Top Quoted Companies</SectionTitle><div className="divide-y divide-slate-100 px-5">{["Waaree Energies", "ABB India", "Growatt India"].map((company, index) => <div key={company} className="flex items-center gap-3 py-4"><span className="grid size-11 place-items-center rounded-full bg-slate-900 text-xs font-black text-white">{company.slice(0,2).toUpperCase()}</span><div className="flex-1"><p className="text-sm font-bold">{company}</p><p className="text-xs text-slate-400">{[312, 264, 219][index]} total quotes</p></div><button className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-teal-700">View</button></div>)}</div></section>
    </div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.8fr)_minmax(310px,.8fr)]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><SectionTitle>Pending Seller Approvals</SectionTitle><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr>{["Seller", "Business", "GST", "Joined", "Actions"].map((x) => <th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan="5" className="p-8 text-center text-slate-400">Loading approvals…</td></tr> : requests.length === 0 ? <tr><td colSpan="5" className="p-8 text-center text-slate-400">No pending seller approvals.</td></tr> : requests.slice(0, 5).map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-bold">{item.name}</p><p className="text-xs text-slate-400">{item.email}</p></td><td className="px-5 py-4 text-slate-500">{item.businessName}</td><td className="px-5 py-4 font-mono text-xs text-slate-500">{item.gstNumber}</td><td className="px-5 py-4 text-slate-500">{new Date(item.createdAt).toLocaleDateString()}</td><td className="px-5 py-4"><div className="flex gap-2"><button title="Approve" onClick={() => act(item.id, "approve")} className="grid size-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><FiCheck /></button><button title="Reject" onClick={() => act(item.id, "reject")} className="grid size-8 place-items-center rounded-lg bg-red-50 font-bold text-red-700">×</button></div></td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white"><SectionTitle>Recent Sellers This Month</SectionTitle><div className="divide-y divide-slate-100 px-5">{recentSellers.length ? recentSellers.map((seller) => <div key={seller.id} className="flex items-center gap-3 py-4"><span className="grid size-11 place-items-center rounded-full bg-emerald-100 text-xs font-black text-emerald-800">{seller.name?.split(" ").map(x => x[0]).join("").slice(0,2)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{seller.name}</p><p className="truncate text-xs text-slate-400">{seller.businessName}</p></div><span className="text-xs text-slate-400">{new Date(seller.createdAt).toLocaleDateString("en", { day: "2-digit", month: "short" })}</span></div>) : sellerAvatars.map((avatar, index) => <div key={avatar} className="flex items-center gap-3 py-4"><span className="grid size-11 place-items-center rounded-full bg-emerald-100 text-xs font-black text-emerald-800">{avatar}</span><div className="flex-1"><p className="text-sm font-bold">{["Rohan Sharma", "Anita Kumar", "Nikhil Mehta"][index]}</p><p className="text-xs text-slate-400">{["R.S. Electricals", "Kumar Solar", "Mehta Controls"][index]}</p></div><span className="text-xs text-slate-400">{["05 Aug", "03 Aug", "01 Aug"][index]}</span></div>)}</div></section>
    </div>
  </div></DashboardShell>;
}
