import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Navigate, useParams } from "react-router-dom";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FiArrowRight, FiBell, FiBox, FiCheckCircle, FiDownload, FiEdit2, FiEye, FiFileText, FiFilter, FiHelpCircle, FiImage, FiMail, FiMessageCircle, FiMoreHorizontal, FiPaperclip, FiPlus, FiSearch, FiSend, FiTrash2, FiUpload, FiUsers, FiX } from "react-icons/fi";
import { enquiries, monthlyData, notices, quotations, sellerLeads, sellerProducts } from "../../data/sellerData";
import { ProfileContent } from "../Profiles/ProfilePage";
import { getSellerQuotations } from "../../services/quotationService";
import { getSellerProducts } from "../../services/productService";
import { useToast } from "../../context/ToastContext";
import { apiMessage } from "../../lib/api";
import SellerReports from "../Seller/Reports";

const card = "rounded-[20px] border border-slate-200 bg-white shadow-[0_4px_24px_rgba(15,23,42,.04)]";
const statuses = { New:"bg-blue-50 text-blue-700", Contacted:"bg-violet-50 text-violet-700", Quoted:"bg-amber-50 text-amber-700", Won:"bg-emerald-50 text-emerald-700", Lost:"bg-red-50 text-red-700", Active:"bg-emerald-50 text-emerald-700", Draft:"bg-slate-100 text-slate-600", Sent:"bg-blue-50 text-blue-700", Accepted:"bg-emerald-50 text-emerald-700", Expired:"bg-red-50 text-red-700", Available:"bg-emerald-50 text-emerald-700", "Low Stock":"bg-amber-50 text-amber-700", "Out of Stock":"bg-red-50 text-red-700" };
const Status = ({children}) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${statuses[children] || "bg-amber-50 text-amber-700"}`}>{children}</span>;
const Head = ({title, subtitle, actions}) => <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-black tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
const Button = ({children, secondary=false, ...props}) => <button {...props} className={`${secondary ? "border border-slate-200 bg-white text-slate-700" : "bg-teal-700 text-white"} inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition hover:-translate-y-0.5 hover:shadow-md`}>{children}</button>;
const Placeholder = ({small=false}) => <span className={`grid shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-400 ${small ? "size-10" : "h-32 w-full"}`}><span className="text-center"><FiBox className="mx-auto"/><small className={small ? "hidden" : "mt-1 block text-[10px]"}>Image Placeholder</small></span></span>;
const ChartBox = ({title, children}) => <section className={`${card} p-5`}><h2 className="mb-5 font-black">{title}</h2><div className="h-64">{children}</div></section>;
const Search = ({value,onChange,placeholder="Search..."}) => <label className="flex min-w-60 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-slate-400"><FiSearch/><input value={value} onChange={onChange} className="w-full bg-transparent text-sm text-slate-700 outline-none" placeholder={placeholder}/></label>;

export function SellerHome() {
 const stats = [["Today's Leads",18,"+12%",FiUsers],["Active Products",26,"+4%",FiBox],["Pending Quotations",7,"+8%",FiFileText],["Unread Messages",12,"+16%",FiMessageCircle]];
 const pipeline = [["New Leads",18],["Contacted",14],["Quotation Sent",9],["Negotiation",6],["Won",4],["Lost",2]];
 return <><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-500">Seller workspace</p><h1 className="mt-1 text-2xl font-black">Welcome back, Seller</h1><p className="mt-1 text-sm text-slate-500">Apex Solar Solutions · Here is today’s lead activity.</p></div><select className="rounded-xl border border-white bg-white/80 px-4 py-2.5 text-xs font-bold shadow-sm"><option>This month</option><option>Last month</option></select></div>
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(360px,1fr)]"><motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className={`${card} p-5 sm:p-6`}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-400">Overall Leads</p><div className="mt-1 flex items-center gap-2"><strong className="text-2xl">348</strong><span className="text-xs font-bold text-emerald-500">↗ 13.02%</span></div></div><button className="text-slate-400"><FiMoreHorizontal/></button></div><div className="mt-4 h-62"><ResponsiveContainer><AreaChart data={monthlyData}><defs><linearGradient id="leadReference" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6366f1" stopOpacity=".18"/><stop offset="1" stopColor="#6366f1" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#eef0f7" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#a1a1aa"}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#a1a1aa"}}/><Tooltip contentStyle={{borderRadius:12,border:0,boxShadow:"0 8px 30px #0001"}}/><Area dataKey="leads" stroke="#6366f1" strokeWidth={3} fill="url(#leadReference)"/></AreaChart></ResponsiveContainer></div></motion.section>
 <div className="grid grid-cols-2 gap-4">{stats.map(([name,value,growth,Icon],i)=><motion.article key={name} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} whileHover={{y:-3}} className={`${card} min-h-36 p-4`}><div className="flex items-start justify-between"><span className={`grid size-9 place-items-center rounded-xl ${["bg-violet-50 text-violet-600","bg-blue-50 text-blue-600","bg-amber-50 text-amber-600","bg-rose-50 text-rose-600"][i]}`}><Icon/></span><FiMoreHorizontal className="text-slate-300"/></div><strong className="mt-4 block text-2xl">{value}</strong><p className="mt-1 text-[11px] text-slate-500">{name}</p><p className="mt-2 text-[10px] font-bold text-emerald-500">↗ {growth} from last month</p></motion.article>)}</div></div>
 <section className={`${card} mt-6 p-5`}><h2 className="font-black">Lead Pipeline</h2><div className="mt-5 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{pipeline.map(([name,count],i)=><div key={name} className="relative rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">{name}</p><strong className="mt-2 block text-2xl">{count}</strong>{i<5&&<FiArrowRight className="absolute -right-5 top-1/2 z-10 hidden text-slate-300 xl:block"/>}</div>)}</div></section>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.7fr]"><ProductTable rows={sellerProducts.slice(0,5)}/><section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Top Lead Locations</h2></div><div className="p-5">{[["Ahmedabad",18],["Pune",15],["Bengaluru",14],["Jaipur",11],["Hyderabad",9]].map(([place,total],i)=><div key={place} className="mb-5 flex items-center gap-3 last:mb-0"><b className="grid size-7 place-items-center rounded-lg bg-slate-100 text-xs">{i+1}</b><div className="flex-1"><div className="flex justify-between text-xs"><span className="font-bold">{place}</span><span>{total}%</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${total*4}%`}}/></div></div></div>)}</div></section></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.8fr]"><LeadsTable rows={sellerLeads.slice(0,6)} compact/><section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Recent Enquiries</h2></div>{enquiries.slice(0,4).map(x=><div key={x.customer} className="border-b border-slate-100 p-4 last:border-0"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{x.customer.split(" ").map(y=>y[0]).join("")}</span><div className="min-w-0"><b className="text-sm">{x.customer}</b><p className="truncate text-xs text-slate-500">{x.message}</p><button className="mt-2 text-xs font-bold text-indigo-600">Reply</button></div><small className="ml-auto whitespace-nowrap text-slate-400">{x.time}</small></div></div>)}</section></div></>;
}

function ProductTable({rows}) { return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">Product Summary</h2></div><div className="overflow-x-auto"><table className="w-full min-w-160 text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr>{["Product","Category","Views","Enquiries","Status","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(x=><tr key={x.id}><td className="px-5 py-3"><div className="flex items-center gap-3"><Placeholder small/><b>{x.name}</b></div></td><td className="px-5 text-slate-500">{x.category}</td><td className="px-5">{x.views}</td><td className="px-5">{x.enquiries}</td><td className="px-5"><Status>{x.status}</Status></td><td className="px-5"><button><FiMoreHorizontal/></button></td></tr>)}</tbody></table></div></section> }
function LeadsTable({rows,compact=false}) { return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">{compact?"Recent Leads":"All Leads"}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-210 text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr>{["Lead ID","Customer","Product","Location","Date","Priority","Status","Actions"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(x=><tr key={x.id}><td className="px-4 py-4 font-mono text-xs">{x.id}</td><td className="px-4"><b>{x.customer}</b><small className="block text-slate-400">{x.company}</small></td><td className="max-w-48 truncate px-4">{x.product}</td><td className="px-4 text-slate-500">{x.location}</td><td className="px-4 text-slate-500">{x.date}</td><td className="px-4"><span className={x.priority==="High"?"text-red-600":x.priority==="Medium"?"text-amber-600":"text-slate-500"}>● {x.priority}</span></td><td className="px-4"><Status>{x.status}</Status></td><td className="px-4"><div className="flex gap-2 text-slate-500"><button title="View"><FiEye/></button><button title="Chat"><FiMessageCircle/></button><button title="Send quote"><FiSend/></button></div></td></tr>)}</tbody></table></div></section> }
export function ProductsPage() { const [search,setSearch]=useState(""); const [drawer,setDrawer]=useState(false); const rows=sellerProducts.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())); return <><Head title="Products" subtitle="Manage your product catalogue and listing visibility." actions={<><Button secondary><FiUpload/>Import</Button><Button secondary><FiDownload/>Export</Button><Button onClick={()=>setDrawer(true)}><FiPlus/>Add Product</Button></>}/><div className="mb-4 flex flex-wrap gap-3"><Search value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/><Button secondary><FiFilter/>Category · Brand · Status</Button></div><ProductTable rows={rows}/><Drawer open={drawer} close={()=>setDrawer(false)} title="Add Product"><ProductForm close={()=>setDrawer(false)}/></Drawer></> }
function ProductForm({close}) { return <form className="space-y-4" onSubmit={e=>{e.preventDefault();close()}}>{["Product Name","Category","Sub Category","Brand","Company","Technology","Stock","Status"].map(x=><label key={x} className="block text-sm font-semibold">{x}<input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-teal-600" placeholder={`Enter ${x.toLowerCase()}`}/></label>)}<label className="block text-sm font-semibold">Description<textarea rows="4" className="mt-2 w-full rounded-xl border border-slate-200 p-4 outline-teal-600"/></label><label className="grid h-32 place-items-center rounded-xl border-2 border-dashed border-slate-200 text-center text-sm text-slate-400"><span><FiImage className="mx-auto mb-2 text-xl"/>Upload product images</span></label><Button><FiCheckCircle/>Save Product</Button></form> }
function Drawer({open,close,title,children}) { return <>{open&&<button className="fixed inset-0 z-40 bg-slate-950/30" onClick={close}/>}<motion.aside initial={false} animate={{x:open?0:"100%"}} transition={{duration:.3}} className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={close} className="grid size-10 place-items-center rounded-xl bg-slate-100"><FiX/></button></div>{children}</motion.aside></> }

export function StockPage(){ const summary=[["Available",21,"text-emerald-700"],["Reserved",4,"text-blue-700"],["Low Stock",3,"text-amber-700"],["Out of Stock",2,"text-red-700"]]; return <><Head title="Stock Status" subtitle="Monitor inventory availability for customer enquiries."/><div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">{summary.map(x=><div className={`${card} p-5`} key={x[0]}><p className="text-sm text-slate-500">{x[0]}</p><strong className={`mt-2 block text-3xl ${x[2]}`}>{x[1]}</strong></div>)}</div><section className={`${card} overflow-hidden`}><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Product","Available","Reserved","Status"].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{sellerProducts.slice(0,12).map(x=><tr className="border-t border-slate-100" key={x.id}><td className="px-5 py-4 font-bold">{x.name}</td><td className="px-5">{x.stock}</td><td className="px-5">{x.id%5}</td><td className="px-5"><Status>{x.stock===0?"Out of Stock":x.stock<10?"Low Stock":"Available"}</Status></td></tr>)}</tbody></table></section></> }
export function LeadsPage(){const [q,setQ]=useState(""); const rows=sellerLeads.filter(x=>(x.customer+x.product+x.id).toLowerCase().includes(q.toLowerCase())); return <><Head title="Lead Management" subtitle="Track requirements and move opportunities through your sales pipeline." actions={<Button><FiPlus/>Create Lead</Button>}/><div className="mb-4 flex flex-wrap gap-3"><Search value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lead, customer, product..."/><Button secondary><FiFilter/>Status · Date · Priority</Button></div><LeadsTable rows={rows}/></> }
export function QuotationsPage(){return <><Head title="Quotations" subtitle="Create, send, and track commercial quotations." actions={<Button><FiPlus/>New Quotation</Button>}/><section className={`${card} overflow-x-auto`}><table className="w-full min-w-210 text-left text-sm"><thead className="bg-slate-50"><tr>{["Quote ID","Customer","Product","Quantity","Price","Status","Created Date","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{quotations.map(x=><tr className="border-t border-slate-100" key={x.id}><td className="px-5 py-4 font-mono">{x.id}</td><td className="px-5 font-bold">{x.customer}</td><td className="px-5">{x.product}</td><td className="px-5">{x.quantity}</td><td className="px-5 font-bold">{x.price}</td><td className="px-5"><Status>{x.status}</Status></td><td className="px-5">{x.date}</td><td className="px-5"><div className="flex gap-3 text-slate-500"><FiEye/><FiEdit2/><FiSend/><FiDownload/></div></td></tr>)}</tbody></table></section></> }
export function CompanyPage(){return <ProfileContent role="Seller"/>}
export function ReportsPage(){return <><Head title="Reports" subtitle="Understand lead quality, product interest, and conversion performance." actions={<Button secondary><FiDownload/>Export Report</Button>}/><div className="grid gap-6 lg:grid-cols-2"><ChartBox title="Monthly Leads"><ResponsiveContainer><AreaChart data={monthlyData}><XAxis dataKey="month"/><Tooltip/><Area dataKey="leads" stroke="#0f766e" fill="#ccfbf1"/></AreaChart></ResponsiveContainer></ChartBox><ChartBox title="Lead Conversion"><ResponsiveContainer><BarChart data={monthlyData}><XAxis dataKey="month"/><Tooltip/><Bar dataKey="conversion" fill="#0f766e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Most Enquired Products"><ResponsiveContainer><BarChart data={sellerProducts.slice(0,6)} layout="vertical"><XAxis type="number"/><YAxis dataKey="brand" type="category" width={65}/><Tooltip/><Bar dataKey="enquiries" fill="#14b8a6" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Customer Locations"><ResponsiveContainer><PieChart><Pie data={[{name:"Gujarat",value:32},{name:"Maharashtra",value:26},{name:"Karnataka",value:20},{name:"Other",value:22}]} dataKey="value" outerRadius={90}>{["#0f766e","#14b8a6","#5eead4","#cbd5e1"].map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartBox></div></> }
export function NotificationsPage(){const [items,setItems]=useState(notices); return <><Head title="Notifications" subtitle="Stay updated on leads, enquiries, and account activity." actions={<Button secondary onClick={()=>setItems(items.map(x=>({...x,read:true})))}><FiCheckCircle/>Mark all read</Button>}/>{["Today","Yesterday","Older"].map(group=><section key={group} className={`${card} mb-5 overflow-hidden`}><h2 className="bg-slate-50 px-5 py-3 text-xs font-black uppercase tracking-wider text-slate-500">{group}</h2>{items.filter(x=>x.group===group).map(n=><div className={`flex items-center gap-4 border-t border-slate-100 p-5 ${!n.read?"bg-teal-50/40":""}`} key={n.id}><span className="grid size-10 place-items-center rounded-full bg-teal-50 text-teal-700"><FiBell/></span><div className="flex-1"><b className="text-sm">{n.title}</b><p className="text-xs text-slate-500">{n.detail}</p></div>{!n.read&&<i className="size-2 rounded-full bg-teal-600"/>}<button onClick={()=>setItems(items.filter(x=>x.id!==n.id))} className="text-slate-400"><FiTrash2/></button></div>)}</section>)}</> }
export function SettingsPage(){const [tab,setTab]=useState("Profile"); return <><Head title="Settings" subtitle="Manage your seller workspace preferences."/><section className={`${card} overflow-hidden`}><div className="flex overflow-x-auto border-b border-slate-200 px-4">{["Profile","Security","Notification Preferences","Appearance","Account"].map(x=><button onClick={()=>setTab(x)} className={`whitespace-nowrap border-b-2 px-4 py-4 text-sm font-bold ${tab===x?"border-teal-700 text-teal-700":"border-transparent text-slate-400"}`} key={x}>{x}</button>)}</div><div className="max-w-2xl p-6"><h2 className="text-lg font-black">{tab}</h2><p className="mt-1 text-sm text-slate-500">Update your {tab.toLowerCase()} preferences.</p><div className="mt-6 space-y-4">{["Display name","Contact email","Phone number"].map(x=><label className="block text-sm font-semibold" key={x}>{x}<input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" defaultValue={x==="Display name"?"Apex Solar Solutions":""}/></label>)}<Button>Save changes</Button></div></div></section></> }
export function HelpPage(){return <><Head title="Help & Support" subtitle="Find answers or contact the MB Store support team."/><section className="rounded-[20px] bg-teal-800 p-8 text-center text-white"><FiHelpCircle className="mx-auto text-4xl"/><h2 className="mt-4 text-2xl font-black">How can we help?</h2><div className="mx-auto mt-5 max-w-xl"><Search value="" onChange={()=>{}} placeholder="Search help articles..."/></div></section><div className="mt-6 grid gap-4 md:grid-cols-3">{[[FiBox,"Product listings","Manage products, images and approval status."],[FiUsers,"Leads & enquiries","Learn how to respond and create quotations."],[FiMail,"Contact support","Email support@mbstore.in for assistance."]].map(([Icon,title,text])=><article className={`${card} p-6`} key={title}><Icon className="text-2xl text-teal-700"/><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></article>)}</div></> }

function LiveStockPage(){
  const {toast}=useToast();
  const [products,setProducts]=useState([]);
  const [loading,setLoading]=useState(true);
  const [search,setSearch]=useState("");
  const [availability,setAvailability]=useState("all");
  useEffect(()=>{let active=true;getSellerProducts({limit:100,sort:"az"}).then(({data})=>{if(active)setProducts(data.data)}).catch(error=>toast(apiMessage(error),"error")).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[toast]);
  const counts={available:products.filter(x=>x.availability==="in_stock").length,low:products.filter(x=>x.availability==="low_stock").length,out:products.filter(x=>x.availability==="out_of_stock").length};
  const query=search.trim().toLowerCase();
  const rows=products.filter(x=>(!query||x.productName.toLowerCase().includes(query))&&(availability==="all"||x.availability===availability));
  const summary=[["Available",counts.available,"text-emerald-700"],["Low Stock",counts.low,"text-amber-700"],["Out of Stock",counts.out,"text-red-700"]];
  const labels={in_stock:"Available",low_stock:"Low Stock",out_of_stock:"Out of Stock"};
  return <><Head title="Stock Status" subtitle="Monitor inventory availability for customer enquiries."/><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">{summary.map(x=><div className={`${card} p-5`} key={x[0]}><p className="text-sm text-slate-500">{x[0]}</p><strong className={`mt-2 block text-3xl ${x[2]}`}>{x[1]}</strong></div>)}</div><div className="mb-4 flex flex-wrap gap-3"><Search value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product name..."/><select value={availability} onChange={e=>setAvailability(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 outline-teal-600"><option value="all">All availability</option><option value="in_stock">Available / High Stock</option><option value="low_stock">Low Stock</option><option value="out_of_stock">Out of Stock</option></select></div>{loading?<section className={`${card} h-64 animate-pulse`}/>:<section className={`${card} overflow-hidden`}><div className="overflow-x-auto"><table className="w-full min-w-160 text-left text-sm"><thead className="bg-slate-50"><tr>{["Product Name","Category","Brand","Availability"].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr className="border-t border-slate-100" key={x.id}><td className="px-5 py-4 font-bold">{x.productName}</td><td className="px-5">{x.categoryName}</td><td className="px-5">{x.brand}</td><td className="px-5"><Status>{labels[x.availability]}</Status></td></tr>)}</tbody></table></div>{!rows.length&&<div className="grid min-h-40 place-items-center border-t border-slate-100 text-sm font-bold text-slate-500">No products match these filters</div>}</section>}</>
}

function LiveLeadsPage(){
  const {toast}=useToast();
  const [q,setQ]=useState("");
  const [requests,setRequests]=useState([]);
  const [loading,setLoading]=useState(true);
  const [selected,setSelected]=useState(null);
  useEffect(()=>{let active=true;getSellerQuotations({limit:100}).then(({data})=>{if(active)setRequests(data.data)}).catch(error=>toast(apiMessage(error),"error")).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[toast]);
  const query=q.trim().toLowerCase();
  const rows=requests.filter(x=>!query||`${x.quotation_number} ${x.customerName} ${x.product_name_snapshot}`.toLowerCase().includes(query));
  return <><Head title="Lead Management" subtitle="Track requirements and move opportunities through your sales pipeline."/><div className="mb-4 flex flex-wrap gap-3"><Search value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lead, customer, product..."/><Button secondary><FiFilter/>Status · Date</Button></div>{loading?<section className={`${card} h-72 animate-pulse`}/>:<QuotationLeadsTable rows={rows} onView={setSelected}/>} {selected&&<LeadRequestPopup request={selected} onClose={()=>setSelected(null)}/>}</>
}

function QuotationLeadsTable({rows,onView}) {
  return <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black">All Leads</h2></div><div className="overflow-x-auto"><table className="w-full min-w-210 text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr>{["Lead ID","Customer","Product","Location","Date","Status","Actions"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(x=><tr key={x.id}><td className="px-4 py-4 font-mono text-xs">{x.quotation_number}</td><td className="px-4"><b>{x.customerName}</b><small className="block text-slate-400">{x.customer_phone||"Phone not provided"}</small></td><td className="max-w-48 truncate px-4">{x.product_name_snapshot}</td><td className="px-4 text-slate-500">{[x.customerArea,x.customerDistrict,x.customerState].filter(Boolean).join(", ")||"Not provided"}</td><td className="px-4 text-slate-500">{new Date(x.created_at).toLocaleDateString("en-IN")}</td><td className="px-4"><Status>{x.status.charAt(0).toUpperCase()+x.status.slice(1)}</Status></td><td className="px-4"><button title="View" onClick={()=>onView(x)} className="text-slate-500"><FiEye/></button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="grid min-h-48 place-items-center border-t border-slate-100 text-sm font-bold text-slate-500">No quotation requests found</div>}</section>
}

function LeadRequestPopup({request,onClose}) {
  const location=[request.customerAddress,request.customerArea,request.customerDistrict,request.customerState].filter(Boolean).join(", ")||"Not provided";
  const details=[["Customer",request.customerName],["Mobile",request.customer_phone||"Not provided"],["Product",request.product_name_snapshot],["Brand",request.brand_snapshot],["Category",request.categoryName],["Quantity",`${request.quantity} units`],["Location",location],["Requested",new Date(request.created_at).toLocaleString("en-IN")],["Status",request.status]];
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><article className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Customer request</p><h2 className="text-2xl font-black">{request.quotation_number}</h2></div><button onClick={onClose} className="grid size-10 place-items-center rounded-xl bg-slate-100"><FiX/></button></div><dl className="mt-5 grid gap-3 sm:grid-cols-2">{details.map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-400">{label}</dt><dd className="font-bold capitalize">{value}</dd></div>)}</dl><div className="mt-4 rounded-xl border p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Customer requirement</p><p className="mt-2 text-sm leading-6 text-slate-700">{request.customer_message||"No additional information provided."}</p></div></article></div>
}

const pageMap = { dashboard: SellerHome, products: ProductsPage, stock: LiveStockPage, leads: LiveLeadsPage, quotations: QuotationsPage, company: CompanyPage, reports: SellerReports, notifications: NotificationsPage, settings: SettingsPage, help: HelpPage };
export default function SellerPages() { const { section } = useParams(); const Page = pageMap[section]; return Page ? <Page /> : <Navigate to="/seller/dashboard" replace />; }
